content/nginx-one/changelog.md
content/nginx-one/glossary.md
content/nginx-one/how-to/certificates/manage-certificates.md
content/nginx-one/how-to/config-sync-groups/_index.md
content/nginx-one/how-to/config-sync-groups/manage-config-sync-groups.md
content/nginx-one/how-to/nginx-configs/_index.md
content/nginx-one/how-to/nginx-configs/add-file.md
content/nginx-one/how-to/nginx-configs/add-instance.md
content/nginx-one/how-to/nginx-configs/clean-up-unavailable-instances.md
content/nginx-one/how-to/nginx-configs/view-edit-nginx-configurations.md
content/nginx-one/how-to/settings/_index.md
static/nginx-one/api/one.json

This is the public release of documentation related to how you can deploy certificates on [Config Sync Groups](https://docs.nginx.com/nginx-one/glossary/).
Note: we had multiple approvals internally, so that meets our requirement for 2 or more approvals for significant new/revised content.
Once published, you can see these changes at
- Code
In these cases, the change will require at least two (2) approvals before …

feat: NGINX One Console. Deploy certs/keys on CSGs, part one

---

LICENSE
README.md

Update license years from 2024 -> 2025 in two locations:
- README.md
- LICENSE
- Code

feat: Update license dates

---

README.md

Many (most) OSS repos for documentation include a link to the URL for the docs, as built. This PR adds the link.
- Code

Include link to docs from README

---

.github/CODEOWNERS

Match existing CODEOWNERS pattern from other doc repositories 
- Code

Add docs-engineering to CODEOWNERS

---

layouts/index.html

Remove mentions of community Slack

Remove mentions of community Slack

---

content/includes/nap-waf/config/v5/host-based-nginx-instructions/common-steps-with-debian.md
content/includes/nap-waf/config/v5/host-based-nginx-instructions/common-steps-with-ubuntu.md

Updated expired references to signing keys
- Code

Updated expired references to signing keys

---

static/nginx-one/api/one.json

Problem: NGINX One API reference spec is out of date.
Solution: Updated based on latest spec from NGINX One.
Testing: N/A
Closes #ISSUE
- Code
- URLs (watch for …

Update N1 API reference with latest specification

---

.github/workflows/daily-deploy.yml

Fix repo and org ref to daily deploy
Problem: Daily deploy job was failing
Solution: This update points to the correct org/repo
Testing: Can be complete when merged to main
Closes #ISSUE
- Code

Fix repo and org ref to daily deploy

---

.github/pull_request_template.md

The pull request template currently renders incorrectly due to a lack of spacing within the square brackets. The spaces looked optional in GitHub documentation, and the issue was not obvious until merged and used.
- [] I have read the [contributing guidelines](/CONTRIBUTING.md)
- [] I have signed the [F5 Contributor License Agreement (CLA)](https://github.com/f5/.github/blob/main/CLA/cla-markdown.md)
- [] I have ensured that documentation content adheres to [the style guide](/templates/style-guide.md)
- [] If the change involves potentially sensitive changes, I have assessed the possible impact
- [] If applicable, I have added tests that prove my fix is effective or that my feature works
- [] If …

feat: Fix pull request template by adding spaces to checkboxes

---

content/nap-waf/v5/configuration-guide/configuration.md

Add documentation for UDS converter in NAP5

---

content/ngf/reference/api.md

Includes changes to the NginxProxy API for the 2.0 release.
Problem: NGINX Gateway Fabric has made changes to the NginxProxy API.
Solution: Update the API reference doc to include changes to NginxProxy API.

Update NGINX Gateway Fabric API Reference

---

.github/workflows/build-push.yml

Autodeploy to prod

---

content/nap-waf/v4/releases/about-4.13.md
content/nap-waf/v5/admin-guide/compiler.md
content/nap-waf/v5/releases/about-5.5.md

Ohad perets patch 3 (fixing some PM comments)

---

layouts/redoc/single.html

- Allow Redoc menu to be scrollable.
**GitHub Issue**:
Closes https://github.com/nginxinc/docs-platform/issues/281

fix: redoc menu content is now scrollable

---

static/sitemap_index.xml

Remove ngf from sitemap_index.xml. 
Since ngf is now part of this repo, it no longer builds it's own sitemap

Remove ngf from sitemap_index

---

content/nap-waf/v4/releases/about-4.12.md
content/nap-waf/v5/releases/about-5.4.md

add ids ro 4.12 & 5.4 RN

---

content/ngf/_index.md

This PR:
- This PR updates the NGINX Gateway Fabric doc set title to align with the style used in other doc sets.

Update NGF doc set title to align with other doc sets

---

content/nginxaas-azure/billing/usage-and-cost-estimator.md

Fixes the path for the CSS and JS files for the NGINXaaS for Azure cost calculator

fix: update css js path for n4a cost calculator

---

content/ngf/how-to/traffic-security/integrating-cert-manager.md

fix: Fix "manage" typo in NGF documentation for Certificate Manager

---

content/nginxaas-azure/changelog.md

Write February instead of Feb , for consistency with the rest of the changelog

fix: fix style in latest n4a changelog entry

---

content/nap-waf/v5/admin-guide/deploy-on-kubernetes.md

Added a missing mount to the nginx container in the NAPv5 Kubernetes deployment file.

fix: add a missing mount in napx deployment file

---

static/sitemap_index.xml

N4A has now been moved to this repo, removing sitemap so coveo can kick back in.
Closes #ISSUE

Remove n4a sitemap

---

content/agent/changelog.md

Adds Agent 2.40 changelog details to the NGINX Agent docs.

docs: add agent 2.40 changelog

---

static/nginx-one/api/one.json

Problem: Staged Configs is not yet in prod, so it should not be in the API docs.
Solution: This MR removes any staged-configs endpoints. 
Testing: N/A

remove staged config endpoints

---

content/nginxaas-azure/app-protect/configure-waf.md

Using polciy JSON everywhere as our code will translate it to tgz post complilation anyway. The service
accepts JSON from the customer as it is easier to
read and updating our docs to just use json in the configuration just streamlines the experience. If
the user finds out that they can use tgz as well,
:shrug:
Please focus on (optional): If you any specific areas where you would like reviewers to focus their …

Use policy json instead of tgz

---

tests/search.spec.ts

Resolves failure seen here: https://github.com/nginx/documentation/actions/runs/13595648655

Resolved duplicate searchbox for Playwright locator

---

go.mod
go.sum

Update theme to 0.42.1

---

.github/workflows/labeler.yml

Changes the `on` target in the github action, which should allow labeler to run, and add labels on PRs from forked repos.

CICD: Change on target of labeler to fix permissions

---

content/nginx-one/api/api-reference-guide.md

Current version of N1C API guide is essentially blank. https://docs.nginx.com/nginx-one/api/api-reference-guide/
Solution: Revert change in this PR: https://github.com/nginx/documentation/pull/287/files#diff-9656c13ed4404f157b0158296fedd11521f8e35e93e1e27f79728a1155420c0fR1
Testing: Built locally

fix: repair N1C API guide

---

content/nap-dos/releases/about-1.2.0.md

feat: Update docs -  Arbitrator 1.2.0

---

CLOSED_CONTRIBUTIONS.md
F5-NGINX-team-notes.md
content/nim/nginx-app-protect/setup-waf-config-management.md

Adds NIM 2.19.1 Release notes and known isses.

NGINX Instance Manager 2.19.1

---

content/agent/technical-specifications.md

Problem: Updates the agent os supported versions
Solution: 
1. Adds support for Alpine 3.21
2. Removes Alpine Linux 3.17 support
3. Removes SLES 12 support
Testing: 
Closes #ISSUE
[^1]: Potentially sensitive changes include anything involving code, personally identify information (PII), live URLs or …

Updates the agent os supported versions

---

content/nginx/admin-guide/installing-nginx/installing-nginx-docker.md

Based on previously approved internal change

Fix - sync with internal change

---

content/agent/install-upgrade/install.md
content/includes/agent/installation/manually-connect-to-console.md

Review of the v3 install guide

docs: review Agent v3 install doc

---

content/agent/install-upgrade/install.md

Change wording to indicate we don't recommend installing Agent as root

docs: Change root wording agent

---

content/nap-dos/releases/about-4.6.md

This commit adds the correct release date for NAP DoS 4.6.
- [ x] I have read the [contributing guidelines](https://github.com/nginx/documentation/blob/main/CONTRIBUTING.md)
- [ x] I have signed the [F5 Contributor License Agreement (CLA)](https://github.com/f5/.github/blob/main/CLA/cla-markdown.md)
- [x ] I have rebased my branch onto main
- [x ] I have ensured my PR is targeting the main branch and pulling from my branch from my own fork
- [x ] I have ensured that the commit messages adhere to [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary)
- [x ] I have ensured that documentation content adheres to [the style guide](https://github.com/nginx/documentation/blob/main/template …

Correct the release date for NAP DoS 4.6

---

content/nap-waf/v4/releases/about-3.9.1.md

Fix Broken link
Closes #ISSUE
[^1]: Potentially …

fix: Update about-3.9.1.md broken link

---

content/nginx/releases.md

Converts the NGINX Plus support list to tables in the Release notes

docs: convert N+ support list to table

---

layouts/redoc/single.html

Closes https://github.com/nginxinc/docs-platform/issues/438
Before:
After (Footer is at the very bottom upon scroll):

Fix container height + add breadcrumbs for redocly

---

content/agent/support.md

Minor updates to the v3 support doc

docs: update agent v3 support doc

---

content/agent/about.md
go.mod
go.sum

docs: about formatting

---

content/ngf/how-to/data-plane-configuration.md

Add missing colon in NGF yaml

---

content/solutions/about-subscription-licenses.md

Fix missing semicolon

---

config/_default/config.toml

SelfService: Add page source edit and issue links param. This param is required to generate view/edit/issue links. See related theme update https://github.com/nginxinc/nginx-hugo-theme/pull/216
Closes 328

SelfService: Add page source edit and issue links param

---

content/nginx-one/rbac/roles.md
static/nginx-one/api/one.json

Follow-up to https://github.com/nginx/documentation/pull/248
- Left out a link that doesn't work (yet)

N1C -- XC-based link update

---

content/nim/releases/known-issues.md

Updates the known issues for NIM based on the current ticket information
Closes #ISSUE

docs: NIM Known issues cleanup

---

.github/workflows/coveo.yml

Fix broken coveo token workflow.

Change endpoint for coveo token updates

---

.github/workflows/coveo.yml

Add echo for debugging for coveo

---

content/nim/nginx-app-protect/setup-waf-config-management.md

Replace an ambiguous ref with the full path
Closes #ISSUE

fix: update ambiguous link

---

content/includes/nginx-one/staged-config-overview.md

Remove redundancy in a sentence:
From "It takes time to set up NGINX configuration files can take time"
To "It takes time to set up NGINX configuration files"

Remove redundant content in staged-config-overview.md

---

content/nim/nginx-app-protect/setup-waf-config-management.md

Fixed typo in NIM docs

---

content/ngf/how-to/data-plane-configuration.md
content/ngf/overview/product-telemetry.md

Update docs for CP/DP split telemetry changes.
Problem: Some small docs changes are needed for the new telemetry metrics/changes introduced with the control data plane split.
Solution: Add the new metrics. Also updated the data plane configuration document small error of including the `namespace` field in the `gateway.infrastructure.parametersRef` field since that does not exist: https://gateway-api.sigs.k8s.io/reference/spec/#localparametersreference. 
Note: Left out GatewayAttachedNginxProxies in the document since I think it falls under the "we collect a count of NginxProxies"
Testing: 
[^1]: Potentially sensitive changes include anything involving code, personally identify information (PII), live URLs …

NGF: Update control data plane split telemetry

---

content/nginx/admin-guide/monitoring/logging.md

Closes #ISSUE
[^1]: Potentially sensitive changes …

Rewrite of the error log and access log sections

---

content/nginxaas-azure/changelog.md

Updated the changelog to highlight the support for custom WAF policies.
Problem: Added more details to the NGINXaaS for Azure changelog to highlight the availability of custom WAF policy creation and deployment.
Testing: N/A

Update NGINXaaS for Azure changelog

---

content/nginx/deployment-guides/amazon-web-services/high-availability-keepalived.md

Reverts nginx/documentation#520

Revert "Revised text and headers to adhere to style guide"

---

content/nim/releases/release-notes.md

fix: Update NIM rns date

---

content/nginx/admin-guide/security-controls/securing-http-traffic-upstream.md

Removal of random symbols introduced in https://github.com/nginx/documentation/pull/512

Removed random symbols introduced in #512

---

.github/workflows/build-push.yml

Added `repository_dispatch` to `build-push.yml`

Add a new trigger to build push workflow

---

content/includes/agent/installation/update-container.md
content/includes/nginx-one/add-file/new-ssl-bundle.md
go.mod
go.sum

- Fixed 2 spelling mistakes encountered in Agent v3 docs

Update Agent v3 docs spelling errors

---

content/nginx-one/how-to/nginx-configs/add-instance.md

Fixes a link that was missing the link itself.

fix nginx one console broken link

---

content/nginx-one/getting-started.md
content/nginx-one/how-to/nginx-configs/add-file.md
content/nginx-one/how-to/nginx-configs/add-instance.md
content/nginx-one/how-to/nginx-configs/clean-up-unavailable-instances.md
content/nginx-one/how-to/nginx-configs/manage-config-sync-groups.md
content/nginx-one/how-to/nginx-configs/view-edit-nginx-configurations.md

Improvements to the NGINX One and Agent v3 docs based on engineer's feedback

NGINX One and Agent v3 docs improvements based on feedback

---

CLOSED_CONTRIBUTIONS.md

The steps dont work without this change
Closes #ISSUE
Before merging a pull request, run through this checklist and mark each as …

Fix CLOSED_CONTRIBUTIONS.md

---

.github/workflows/build-push.yml

- Updated Slack workflow with new PAT 
- Small fixes to quotes

Updated Slack workflow with new PAT + small fixes to quotes

---

.github/workflows/build-push.yml

Switched to use the correct PAT for the API call.

Fixed Slack workflow with correct PAT

---

content/unit/changes.md
content/unit/community.md
content/unit/configuration.md
content/unit/installation.md

- Minor formatting fixes after a visual inspection of the docs
- Add an update to the community doc that was applied to unit.nginx.org but slipped through the cracks here

Unit docs minor formatting fixes

---

content/ngf/overview/gateway-api-compatibility.md

Add allowedListeners to gateway api compatibility doc.

NGF: Add allowedListeners to gateway api compatibility doc

---

content/nginx/releases.md

Reviewed and approved in the internal repo.

NGINX Plus R34 P1 Release Notes

---

content/nginx-one/about.md
content/nginx-one/glossary.md

From issue #625
'I wonder if we can tuck the legal blurb at the bottom of this doc somewhere else -- it's a bit awkward to lead with it.
Right now it reads like:
“Here are the great things you can do with NGINX One. But first, a word from the lawyers.”'
Solution: Moved content to the bottom of the glossary
Closes #625 

enhancement: Move legal notice to an appropriate location

---

content/nginx-one/connect-instances/connect-nginx-plus-container-images-to-nginx-one.md

- Fixes a broken link on N1 footer
- Changes absolute links to refs

fix N1 footer link

---

content/nginxaas-azure/troubleshooting.md

Adds a dummy doc to set up a redirect to the troubleshooting KB.
To merge once the KB article is ready

dummy doc for redirect

---

content/nginx-one/_index.md

Resolved https://f5.slack.com/archives/C07DXE3E5HA/p1749452912914449

Resolved dot org link in N1 landing page

---

content/nginx-one/_index.md

Change reference of `Product` to `Components` in N1 landing page.

Renamed from products to components for N1

---

content/ngf/overview/gateway-api-compatibility.md

A quotation was missing that was not caught by the original PR pipeline.

Fix missing quote

---

.github/workflows/notification.yml

Renamed from `SLACK_WEBHOOK_URL` to `SLACK_WEBHOOK_URL_DOCS_INCIDENT` in `notification.yml` workflow.

Changed variable name for Slack webhook in notification workflow

---

.github/workflows/build-push.yml

Adding quotes to the object to send slack notification on build

Small fix to add quotes to build-push for slack

---

content/nim/deploy/vm-bare-metal/install.md
content/nim/disconnected/offline-install-guide.md

This PR fixes two broken links in the NIM deployment guides.

fixed broken links in NIM deployment guides

---

content/nginx/admin-guide/installing-nginx/installing-nginx-docker.md

Fixes a broken link caused by a recent change in the NGINX One console docs
Closes #700 

fix: broken link fixed in Nplus install docker guide

---

.github/workflows/build-push.yml

Bump docs-action version in `build-push.yml` to `v1.0.9`

Bump docs-action to 1.0.9 from 1.0.8 in Build workflow

---

content/amplify/changelog.md
content/amplify/known-issues.md

NGINX Amplify catalog audit missing metadata.

docs: AMP catalog audit

---

content/nginx/admin-guide/security-controls/configuring-oidc.md
content/nginx/deployment-guides/single-sign-on/active-directory-federation-services.md
content/nginx/deployment-guides/single-sign-on/auth0.md
content/nginx/deployment-guides/single-sign-on/cognito.md
content/nginx/deployment-guides/single-sign-on/entra-id.md
content/nginx/deployment-guides/single-sign-on/keycloak.md
content/nginx/deployment-guides/single-sign-on/okta.md
content/nginx/deployment-guides/single-sign-on/onelogin.md
content/nginx/deployment-guides/single-sign-on/ping-identity.md
content/nginx/variables.md

Adds the missing catalog metadata for NGINX + docs.

docs: update catalog for NGINX+

---

content/nic/usage-reporting.md

This is a test PR to check whether the kic team's access to the repository is configured correctly.
Additionally fix two tiny markdown lint violations.

Fix blank line around fences violation

---

content/nic/installation/installing-nic/installation-with-operator.md

feat: Update NGINX Ingress Helm Operator links from nginxinc to nginx

---

content/ngf/_index.md
content/nic/_index.md

feat: Add logo parameters to NGINX Ingress Controller & Gateway Fabric

---

content/nginx-one/_index.md

Updates custom N1 landing page to be visible using new params.

Updated N1 landing page to use new params

---

go.mod
go.sum

Bump theme version from `v0.42.37` to `v0.43.2`

Bump theme version

---

_banners/agent-v3-release.md

Updates the Agent v3 compatibility notification to include NIM as not supported by v3.

docs: add nim to Agent v3 notice

---

content/nap-dos/releases/about-1.2.0.md
content/nap-dos/releases/about-4.4.md
content/nap-dos/releases/about-4.5.md
content/nap-dos/releases/about-4.6.md

Add missing NAP-DOS docs to catalog

docs: add missing NAP-DOS docs to catalog

---

content/agent/installation-upgrade/installation-unprivileged.md

Add a missing doc to the Agent documentation catalog

docs: Agent catalog audit

---

documentation/maintainers-etiquette.md

Fix broken link: maintainers-etiquette.md

---

content/ngf/changelog.md
content/ngf/get-started.md
content/ngf/how-to/control-plane-configuration.md
content/ngf/how-to/data-plane-configuration.md
content/ngf/how-to/scaling.md
content/ngf/how-to/upgrade-apps-without-downtime.md
content/ngf/install/deploy-data-plane.md
content/ngf/install/nginx-plus.md
content/ngf/install/secure-certificates.md
content/ngf/install/upgrade-version.md
content/ngf/monitoring/dashboard.md
content/ngf/monitoring/tracing.md
content/ngf/overview/custom-policies.md
content/ngf/overview/gateway-architecture.md
content/ngf/overview/nginx-plus.md
content/ngf/overview/product-telemetry.md
content/ngf/reference/api.md
content/ngf/reference/cli-help.md
content/ngf/reference/technical-specifications.md
content/ngf/traffic-management/advanced-routing.md
content/ngf/traffic-management/client-settings.md
content/ngf/traffic-management/mirror.md
content/ngf/traffic-management/request-response-headers.md
content/ngf/traffic-management/snippets.md
content/ngf/traffic-management/tls-passthrough.md
content/ngf/traffic-management/upstream-settings.md
content/ngf/traffic-security/secure-backend.md

Add missing NGF docs to the catalog
(The linter picked up a few unnecessary blank spaces)

docs: add missing NGF docs to the catalog

---

content/nginx/technical-specs.md

A small and simple PR that makes the names of dynamic modules in Tech Specs clickable

Added URLs to dynamic modules in Tech Specs.

---

content/nginx-one/_index.md

Update N1 landing page to match new landing page archetype

Update the NGINX One landing page for mainframe

---

config/_default/config.toml
config/production/config.toml

Addresses deprecration notices that were introduced with recent Hugo version updates
```
WARN  deprecated: site config key privacy.twitter.enableDNT was deprecated in Hugo v0.141.0 and will be removed in a future release. Use privacy.x.enableDNT instead.
WARN  deprecated: the ":filename" permalink token was deprecated in Hugo 0.144.0 and will be removed in a future release. Use ":contentbasename" instead.
```
Problem: Some variables in config.toml got renamed on the Hugo side.
Solution: Simple renames.
[^1]: Potentially sensitive changes include anything involving code, …

chore: config.toml deprecation fixes

---

content/nginx-one/agent/containers/run-agent-container.md

Remove Placeholder text and replace with actual container registry URL.
Closes #ISSUE
[^1]: Potentially sensitive changes include anything involving code, personally identify information …

Update NGINX Agent container instructions

---

content/agent/_index.md

Updates the NGINX Agent v2 docs landing page to the new format with featured docs and cards

docs: add new Agent landing page

---

content/nic/installation/installing-nic/_index.md
content/nic/installation/integrations/_index.md
content/nic/installation/nic-images/_index.md

NIC: Fix old nic urls

---

content/includes/nim/tech-specs/supported-distros.md

Updated the NIM technical specification document to reflect unsupported OS distributions.
Testing: Tested locally.
Closes # N/A

fix: updated the unsupported OS list

---

content/nginx-one/_index.md

Removed unneeded usages of `isFeatured` param for Cards shortcode.

Removed unneeded `isFeatured` param for cards

---

layouts/index.html

Update link on mainframe for NGINX unit to be correct.
https://github.com/user-attachments/assets/82529bb9-f923-4d38-a4f7-309fcd01cfee

Update on mainframe the correct url for Unit

---

content/includes/licensing-and-reporting/apply-jwt.md
content/includes/licensing-and-reporting/deploy-jwt-with-csgs.md
content/solutions/about-subscription-licenses.md

This PR:
- Corrects a reference to the NGIXN One Console
- Removes `docs` from include metadata (not needed)

edits to about subscription licenses

---

CONTRIBUTING.md

Include option to clone in CONTRIBUTING.md

---

content/nginx-one/connect-instances/set-up-nginx-proxy-for-nginx-one.md

Add v3 steps to config Agent to use the proxy, in a tab.
Closes #822 

docs: update v3 steps for NGINX One config proxy

---

content/agent/technical-specifications.md

Small PR to update the versions under Technical specifications.
Closes #ISSUE

Update compatibility table in Technical specifications

---

content/nap-dos/deployment-guide/learn-about-deployment.md

Rnitzan dos release 4.7

---

content/nic/tutorials/security-monitoring.md

- Updates manifest instructions to enable NAP security monitoring from NIC
[^1]: Potentially sensitive information includes personally identify information (PII), authentication credentials, and live URLs. Refer to the [style guide](/documentation/style-guide.md) for guidance about placeholder content.

fix: update nic docs

---

content/agent/technical-specifications.md

Updated NGINX Agent V2 supported distributions to include RedHat 10 & Ubuntu 25.04/24.04
Removed RH7, Alma7 and Centos 7. 
Update supported Alpine versions
[^1]: Potentially sensitive information includes personally identify information (PII), authentication credentials, and live URLs. Refer to the [style guide](/documentation/style-guide.md) for guidance about placeholder content.

Docs: Update supported OS's for agent V2

---

tests/utils/commonUtils.ts

- Fixed issue with `UI Validation` workflow failing sometimes due to consent form not being clicked.

Fix UI validation issue with clicking consent

---

content/nic/installation/installing-nic/installation-with-manifests.md

fix: Remove last remaining old-style call-out

---

content/nginxaas-azure/_index.md

Fix issue with Azure landing page

Fix rendering issues on azure landing page

---

.github/workflows/linkchecker.yml

Yesterdays change didn't work as it seems to be case sensitive.
I'm removing yesterdays change and instead updating an existing ignore value that will cover both instances of 
- https://insert_your_tenant_name.console.ves.volterra.io/
- https://insert_your_tenant_name.console.ves.volterra.io
[//]: # "Finish by noting anything beyond the scope of the PR changes …

Update linkchecker action

---

content/includes/nginx-plus/supported-distributions.md
content/nginx/admin-guide/dynamic-modules/acme.md
content/nginx/admin-guide/dynamic-modules/dynamic-modules.md
content/nginx/admin-guide/dynamic-modules/opentelemetry.md
content/nginx/admin-guide/installing-nginx/installing-nginx-open-source.md
content/nginx/admin-guide/installing-nginx/installing-nginx-plus.md
content/nginx/admin-guide/monitoring/live-activity-monitoring.md
content/nginx/admin-guide/security-controls/configuring-oidc.md
content/nginx/admin-guide/yaml/v9/nginx_api.yaml
content/nginx/open-source-components.md
content/nginx/releases.md
content/nginx/technical-specs.md
content/solutions/about-subscription-licenses.md

NGINX Plus R35.

---

content/nap-waf/v5/releases/about-5.8.md

feat: Fix NAP 5.8 R35 note

---

.github/workflows/coveo.yml

Update the users for generating a new JWT token for coveo. Done in order to get certain sources to show up

Add new user to jwt token generation for coveo

---

content/ngf/how-to/data-plane-configuration.md

Update the documentation on how to use the NginxProxy patch functionality to use more descriptive and informative examples.

NGF: Update examples in NginxProxy patch documentation

---

content/agent/installation-upgrade/upgrade.md

* Remove reference to an unsupported OS from the NGINX Agent Upgrade guide.
[//]: # …

Remove unsupported os reference

---

content/nginx-one/workshops/lab1/getting-started-with-nginx-one.md

This PR:
- Rewords the NGINX Agent description in the NGINX One > Workshops > Lab 1 topic.

Edited the NGINX Agent overview in the N1 Workshop Lab 1

---

content/nginx/_index.md

Fix accidental link to NIM RN url

Link to wrong rn

---

content/amplify/known-issues.md
content/nim/releases/known-issues.md
content/nms/acm/releases/known-issues.md
content/nms/acm/releases/release-notes.md

- Remove `rn-styles` shortcode usage

Fix rn-style shortcode usage issues in build

---

content/includes/agent/tech-specs.md

Add supported telemetry section to Agent V3 tech specs

---

content/agent/installation-upgrade/container-environments/docker-support.md

Fixed the broken Docker file link that was mentioned in https://github.com/nginx/agent/issues/1087 (Issue #1087)
NGINX Documentation Issue number: #1051
The pull request fixes the URL link in the NGINX Agent documentation Dockerfile URL to the updated URL.
I changed it through clicking the 'edit page' button located at the bottom of the documentation page then editing it in the forked version before committing it and creating a PR.
The changes will not affect anything else but it might be affected in the future if the structure of the NGINX Agent repository changes again.
Additional Context: 
I am new to the world of contributing, please let me know if I am doing anything wrongly, thank you!
[//]: # "You can …

fix: docker-support.md

---

.github/workflows/linkchecker.yml

Linkchecker: fix misplaced param

---

content/nginx/admin-guide/installing-nginx/installing-nginx-docker.md

Fixed broken anchor in NGINX Plus docs

Fixed broken anchor in NGINX Plus docs

---

content/nginxaas-azure/changelog.md

Updated the date format in the changelog
[//]: # "If the changes were defined by a …

docs: update date for latest entry

---

content/nap-waf/v5/admin-guide/policy-lifecycle-management.md

fix: WAFMC-13098 Update PLM Installation Section

---

content/nginxaas-azure/changelog.md
content/nginxaas-azure/module-changelog.md

- Notification on R35 release in preview channel
- Add the module changelog of R35 in preview
[//]: # "For expediency, you can use screenshots to show small before and after …

NLB-6922: Notification on R35 release

---

content/nginxaas-azure/changelog.md

Update NGINXaaS for Azure's changelog to mention connectivity tool

Update NGINXaaS for Azure's changelog to mention connectivity tool

---

content/nic/configuration/virtualserver-and-virtualserverroute-resources.md

remove an extra space in an example
[//]: # "If the changes were defined by a …

docs: Fix path formatting for green tea route

---

.github/workflows/linkchecker.yml

Update the linkchecker url for waf as it has changed.
[//]: # "If the changes were …

Update linkchecker waf url

---

content/nginx-one/agent/configure-instances/configure-agent-features.md

Add a document to configure Agent features under nginx-one/agent

docs: Agent/add missing doc

---

content/nginx-one/changelog.md

Update changelog.md for N1C Instance Observability M3 release
[//]: # "If the …

docs: update changelog.md for N1C Instance Observability M3 release
