nginx/documentation

content/nim/fundamentals/tech-specs.md

Updated tech specs to account for this issue:
https://github.com/nginxinc/docs/issues/1528
Closes #ISSUE
- Code
- Make sure to …

Update tech-specs.md for ev reporting

---

content/nim/admin-guide/authentication/oidc/keycloak-setup.md

Problem: To configure OpenID Connect with Keycloak for NIM authentication, there are new instructions for Keycloak >18 due to UI changes on the latest version.
Solution:  We added those new steps in the documentation. 
Testing: Instructions validated and tested by dev and qe
- Code

Update keycloak-setup.md for Keycloak > 18

---

CONTRIBUTING.md

This commit adds a section on the repo's branch protection rules to the CONTRIBUTING doc.
Closes #ISSUE
Before creating a PR, run …

Document the repo's branch protection rules

---

CONTRIBUTING_DOCS.md
content/nginx-one/getting-started.md
content/nginx-one/how-to/data-plane-keys/create-manage-data-plane-keys.md
content/nginx-one/how-to/nginx-configs/add-instance.md

Fix outdated NGINX One documentation around data plane key deletion (steps through the console workflow, rather than documenting an API-only solution).
Clarify NGINX Agent installation in NGINX One documentation, primarily around necessary firewall permissions.
- Code

fix: update how to delete deta plane keys

---

content/amplify/faq/nginx-amplify-agent.md
content/amplify/nginx-amplify-agent/install/installing-amplify-agent.md
content/nap-waf/v4/logging-overview/security-log.md
content/nap-waf/v5/logging-overview/security-log.md

Updates from internal changes through Jan 6
- Code

Updates from internal changes, thru Jan 6

---

content/nginx/admin-guide/dynamic-modules/lua.md

Closes #ISSUE
- Code
- Anything that resembles Personally …

NGINX Plus admin guide: Added lua_stream to Lua Dynamic Module

---

content/includes/licensing-and-reporting/configure-nginx-plus-report-to-nim.md
content/solutions/about-subscription-licenses.md

This PR makes two improvements to the way we show notes about self-signed certificates:
1. It removes repeated notes to keep things clear and simple.
2. It fixes a formatting issue that made the note hard to read and caused it to scroll awkwardly.
https://github.com/user-attachments/assets/a458d7e0-6d31-4ec0-9125-0f03c5fa77da

Resolve duplicate and scrolling note for self-signed certs

---

content/nap-waf/v4/admin-guide/upgrade-nap-waf.md

Fix broken link in nginx-app-protect-waf
Problem: Automation found broken link in nginx-app-protect-waf docs. https://github.com/nginx/documentation/actions/runs/12685140469/job/35354980039
Possibly caused by Azure content update.
Solution: URL is updated.
Testing: Local testing, URL opens correctly. No more 404
- Code

Fix broken link in upgrade-nap-waf.md

---

content/nginx-one/how-to/certificates/manage-certificates.md

Based on #62 
Here's a screenshot of the build of my proposed change:
Closes #62 
- Code

fix: Reorganize docs on NGINX One Console certificates into a table

---

content/ngf/how-to/_index.md
content/ngf/how-to/monitoring/_index.md
content/ngf/how-to/traffic-management/_index.md
content/ngf/how-to/traffic-security/_index.md
content/ngf/installation/_index.md
content/ngf/installation/installing-ngf/_index.md
content/ngf/overview/_index.md
content/ngf/reference/_index.md

This commit adds an explicit URL to the subfolders of the NGINX Gateway Fabric set, which is inherited by the pages within the folders. It is necessary for URLs to resolve sensibly, as otherwise they default to the folder path, /ngf/, which we do not map as part of the deployment.
- [] I have read the [contributing guidelines](/CONTRIBUTING.md)
- [] I have signed the [F5 Contributor License Agreement (CLA)](https://github.com/f5/.github/blob/main/CLA/cla-markdown.md)
- [] I have ensured that documentation content adheres to [the style guide](/templates/style-guide.md)
- [] If the change involves potentially sensitive changes, I have assessed the possible impact
- [] If applicable, I have added tests that …

feat: Add explicit URL parameter to Gateway Fabric index pages

---

content/includes/nap-waf/config/v5/build-nginx-image-oss/build-alpine.md
content/includes/nap-waf/config/v5/build-nginx-image-plus/build-alpine.md
content/nap-waf/v4/admin-guide/install.md
content/nap-waf/v5/admin-guide/compiler.md
content/nap-waf/v5/admin-guide/deploy-on-docker.md
content/nap-waf/v5/admin-guide/deploy-on-kubernetes.md
content/nap-waf/v5/admin-guide/install.md
content/nap-waf/v5/admin-guide/overview.md
content/nap-waf/v5/admin-guide/upgrade-nap-waf.md

As part of the NGINX App Protect WAF 5.5 release, Alpine 1.19 support has been added. This commit updates the relevant sections of documentation that mention Alpine support, while also fixing up the metadata for some related pages.

feat: Add Alpine 1.19 support to NGINX App Protect WAF documentation

---

content/nap-waf/v5/configuration-guide/configuration.md

add brute force configuration
Closes #ISSUE
https://jira.f5net.com/browse/WAFMC-10867

Update configuration.md with bf section

---

content/nap-waf/v5/admin-guide/upgrade-nap-waf.md

Problem: WAF enforcer-only upgrade
Solution: Version matching requirements are added

WAF enforcer-only upgrade comment

---

content/includes/nap-waf/config/v5/build-nginx-image-oss/build-alpine.md
content/nap-waf/v4/configuration-guide/configuration.md
content/nap-waf/v5/admin-guide/deploy-on-docker.md

feat: Additional updates/fixes for NAP 5.5 release

---

.github/CODEOWNERS

This commit adds the NGINX Gateway Fabric team as codeowners of the NGF subfolders related to the product, ensuring they get tagged when relevant. As part of this change, I have also alphabetized the teams and adjusting the spacing for readability.

feat: Add NGINX Gateway Fabric to CODEOWNERS, alphabetize file

---

content/nap-waf/v5/admin-guide/compiler.md
content/nap-waf/v5/configuration-guide/configuration.md

Add directory warning, fix UDS issue

---

content/ngf/how-to/monitoring/prometheus.md
content/ngf/how-to/traffic-management/routing-traffic-to-your-app.md
content/ngf/how-to/traffic-security/integrating-cert-manager.md

Fix image and json urls in ngf.
Testing: Images and json were deployed properly, but the urls in `md` weren't updated as part of the migration. The new urls were manually validated.
ssue](https://github.com/nginx/documentation/issues) on GitHub, ensure that you link to it here:

Fix image and json urls in ngf

---

content/nap-waf/v5/admin-guide/compiler.md
content/nap-waf/v5/admin-guide/overview.md

feat: Add Update App Protect Signatures placeholder section

---

content/nginx/deployment-guides/single-sign-on/active-directory-federation-services.md
content/nginx/deployment-guides/single-sign-on/auth0.md
content/nginx/deployment-guides/single-sign-on/cognito.md
content/nginx/deployment-guides/single-sign-on/keycloak.md
content/nginx/deployment-guides/single-sign-on/okta.md
content/nginx/deployment-guides/single-sign-on/onelogin.md
content/nginx/deployment-guides/single-sign-on/ping-identity.md

This PR fixes several `see-also` call-outs that weren't resolving in NGINX Deployment guides.
Closes #128 

fix: fixed see-also call-outs that weren't resolving in NGINX Plus deployment guides

---

content/ngf/how-to/data-plane-configuration.md
content/ngf/overview/gateway-api-compatibility.md

Problem: The documentation for NGF's NginxProxy API needs to be updated now that NGF supports attaching NginxProxy resources to Gateways.
Solution: Updates the Gateway API Compatibility doc to list Gateway Infrastructure field as partially supported. Also, updates the data plane configuration how-to to describe how to attach NginxProxy resources to Gateways and GatewayClasses.
Testing: Checked the rendered documentation.

Update NGF documentation on how to use NginxProxy 

---

content/ngf/how-to/data-plane-configuration.md
content/ngf/how-to/monitoring/dashboard.md
content/ngf/reference/api.md

Problem: The Nginx Plus dashboard document needs to be updated with information on configuring access to it.
Solution: Add a section in `dashboard.md` giving a brief overview on how to change access to the dashboard with an example and a link to the data plane configuration document for more information. Additionally updated the `api.md` document to reflect the current state for NGF on main.
Testing: Checked the rendered documentation.

Nginx plus dashboard additions

---

content/nim/deploy/vm-bare-metal/install.md

Missing command detail, based on feedback
Once we've clarified whether this applies to other commands, we'll move it from Draft to Review
The new command seems to work in my RHEL 9 VM

Update update command for RHEL NIM install

---

content/includes/nap-waf/policy.html
content/nap-waf/v4/configuration-guide/configuration.md
content/nap-waf/v5/configuration-guide/configuration.md

fix: brute force docs

---

content/includes/nginx-one/add-file/edit-config-tip.md
content/includes/nginx-one/add-file/existing-ssl-bundle.md
content/includes/nginx-one/add-file/new-ssl-bundle.md
content/includes/nginx-one/add-file/overview.md
content/nginx-one/how-to/certificates/manage-certificates.md
content/nginx-one/how-to/config-sync-groups/add-file-csg.md

**Problems:** 
Lack of clarity in certificates. NGINX supports certificates in three categories:
- Website traffic (typically purchased from a CA)
- Repo verification
- F5 License verification
Similar processes for adding / editing certs in an Instance / Config Sync Group
Clarification needed on the types of certs that are supported
**Solution:** 
- Added [table](https://frontdoor-test-docs.nginx.com/previews/docs/82/nginx-one/how-to/certificates/manage-certificates/#overview) for different categories of certs
- Added more [detailed description ](https://frontdoor-test-docs.nginx.com/previews/docs/82/nginx-one/how-to/certificates/manage-certificates/#ssltls-certificates-and-more) of different types of supported certs
- Set up
- Distinct files for adding / including certs for both …

fix: Update cert instructions for NGINX One Console

---

static/scripts/install-nim-bundle.sh

This MR contains below two changes 
1. It will send a request to pkgs.nginx.com for tracking how many online/offline installs are done using the script. 
2. It will support generating the fqdn name for generating nim certificates. 

fix: updating script to track offline installations

---

static/scripts/install-nim-bundle.sh

This MR will contains changes identified after nim 2.19.0 release went yesterday. Below are the issue details.
1.  When using -f fqdn option, the new certs are not generated unless existing certs are deleted. So added the change to delete existing certs and generate new certs using the -f option. 
2. Redhat systems are downgrading the nim to 2.18.0 because of the logic issue. Fixed and verified it. 

fix: fixing issues found in 2.19.0 testing

---

content/ngf/how-to/traffic-management/advanced-routing.md
content/ngf/overview/gateway-api-compatibility.md

Problem: Users need updated documentation for regex matching header and query params for HTTPRoutes and GRPCRoutes
Solution: Adds documentation for advanced routing and gateway compatibility document.
Testing: [Deploy preview ](https://frontdoor-test-docs.nginx.com/previews/nginx-gateway-fabric/3093/)
NGF Repository Story - https://github.com/nginx/nginx-gateway-fabric/issues/1965 …

Update docs for regex matching for HTTPRoutes and GRPCRoutes

---

content/controller/_index.md
content/mesh/_index.md
content/modsec-waf/_index.md
content/success.md

This PR:
- Unpublishes docs for the following products that are EOSL:
- NGINX Controller
- NGINX Service Mesh
- NGINX Management Suite

Unpublished docs for Controller, Service Mesh, NMS

---

content/includes/nim/tech-specs/nim-app-protect-support.md
content/nim/nginx-app-protect/setup-waf-config-management.md

Updated the compatibility matrices in Technical Specifications for NGINX App Protect Releases 4.13.0 and 5.5.0. Also updated the nms-nap-compiler versions that correspond to those NAP releases.
Testing: Tested locally.
Closes # N/A

docs: update the NAP and NIM versions for NAP 4.13 and 5.5.0

---

content/nim/deploy/kubernetes/deploy-using-helm.md

Fixed the image paths and added a new `secmon` image to `values.yaml` file for NIM k8s helm deployment as part of NIM v2.19.0 release.
Testing: Tested locally.
Closes # N/A

fix: update k8s values file to include secmon image for NIM K8s deployment

---

.github/pull_request_template.md
archetypes/concept.md

This commit updates the links from the PR templates to use the actual GitHub links: they are currently relative links that do not parse as intended, instead linking to parts of the GitHub website.
It also fixes an issue in the Tutorial archetype's inline Markdown guidance caused by an unintentionally escaped quotation mark.

feat: Update PR links to GitHub URLs, fix inline Tutorial guidance

---

content/includes/nim/templates/additional-templating-resources.md

This PR:
- Adds a link in the _Additional Templating Resources_ section to the NGINX Instance Manager example templates on the DevCentral GitHub.
- Uses a download icon to clearly indicate the user action.

Add link to NGINX Instance Manager config templates on DevCentral's GitHub

---

content/nginxaas-azure/billing/usage-and-cost-estimator.md

Use full path for cost calculator imports temporarily.
The cost calculator should use the normal hugo approach to pulling in scripts and css, but this will fix the nginxaas migration for now.
*note* This will not work in previews, only in dev/staging/production where the hardcoded url matches.

Use full path for cost calculator imports temporarily

---

content/includes/nim/tech-specs/supported-distros.md
content/nginx/deployment-guides/amazon-web-services/high-availability-network-load-balancer.md

- Updated tech specs table for NIM to support ubuntu24
- Fixed syntax errors causing `make docs`/`make watch` failure.
**Testing:** Local testing performed.
**NIM Tech spec Table:**
**Fixed a couple of syntax errors for NGNIX docs:**
Closes #ISSUE
[^1]: Potentially sensitive changes include anything involving code, personally identify information (PII), live URLs or significant amounts of new or revised documentation. Please refer …

fix: updating tech specs table for NIM to support ubuntu24

---

content/nim/deploy/kubernetes/deploy-using-helm.md

- Correcting the SCC link for OpenShift v4.13
- Adding a note with OpenShift version
Testing: tested locally.
Closes #ISSUE
[^1]: Potentially sensitive changes include anything involving code, personally identify information (PII), live URLs or significant amounts of new or revised documentation. Please refer to [our style guide](https://github.com/nginx/documentation/blob/main/templates/style-guide.md) for guidance about …

fix: correcting the SCC link for OpenShift

---

content/ngf/overview/gateway-api-compatibility.md

Some fields were missing from the NGF compatibility doc, so adding those.

Update NGF compatibility doc

---

content/nim/nginx-app-protect/setup-waf-config-management.md

Updated references to NGINX Management Suite into NGINX Instance Manager
Fixed configuration error in App Protect logging example

Removed NGINX Management Suite references, fixed configuration syntax error

---

content/nginxaas-azure/getting-started/ssl-tls-certificates/overview.md

Problem: NGINXaaS returns various certificate errors to the user to assist them in fixing their deployments. Some of these user-facing errors point to this documentation but there isn't a corresponding certificate errors entry.
Solution: Adds the following error codes to the NGINXaaS certificate errors list:
- NoCertificateContent
- MissingContentType
- UnrecognizedContentType
- PKCS12ParseFailure
- PEMParseFailure
Closes [Failed Customer Deployment Creation in swedencentral](https://github.com/nginxinc/nalb-shared/issues/1621)
[^1]: Potentially sensitive changes include anything involving code, personally identify information (PII), live URLs or significant amounts of new or revised documentation. Please …

Add missing NGINXaaS certificate error descriptions and resolutions

---

content/ngf/how-to/data-plane-configuration.md

Problem: Added support for running NGINX in debug mode in NGF's CP-DP split which changes the old way to run NGINX in debug mode.
Solution: Update docs to show new way to run NGINX in debug mode.
Testing: Generated documentation using `make watch`.

Add documentation on running NGINX in debug mode

---

content/includes/ngf/installation/upgrade-api-resources.md
content/ngf/get-started.md
content/ngf/installation/installing-ngf/helm.md
content/ngf/installation/installing-ngf/manifests.md

This commit adds explicit guidance at the top of the Get started guide, directing the reader towards the Installation section for a production deployment. It also removes mention of the experimental channel, which is an unnecessary use case for trying NGF.
It also creates uniformity in the Helm and Manifest deployment documentation, by matching how sections are formatted, and creating an include file for identical instructions on upgrading the API resources. …

feat: Update NGF Get started guide and installation documents

---

content/ngf/installation/nginx-plus-jwt.md

Problem: With the new NGF architecture incoming, the process for setting up NGINX Plus is slightly different than before.
Solution: Update the docs to remove unnecessary steps and add extra context around creating NGINX Plus Secrets.

Update NGINX Plus secrets docs for NGF split

---

static/nginx-one/api/one.json

Problem: The phrases "NGINX One console"  and "the NGINX One Console" in static/nginx-one/api/one.json don't conform to style updates. 
Solution: Changed all instances of "NGINX One console" to "NGINX One Console" and removed the article "the" in front of any relevant instances. 
Testing: N/A
Please focus on (optional): There are two more files with the specific phrase "NGINX One console", I can open separate PRs to fix both of those but I figured I would start with one.
#228 (only addresses a small portion of the issue)
[^1]: Potentially sensitive changes include anything involving …

Update product titles and articles in one.json

---

content/ngf/reference/cli-help.md

Add new CLI field and update CLI name for the changes in the split feature.

Update NGF CLI doc for new feature

---

.github/CODEOWNERS

This commit updates the CODEOWNERS file to add lines for the n4a-docs team, responsible for maintaining the documentation for NGINXaaS for Azure.

feat: Add NGINXaaS for Azure team as CODEOWNERS for their documentation

---

content/nim/nginx-app-protect/setup-waf-config-management.md

URI in `curl -X POST 'https://{{NMS_FQDN}}//api/platform/v1/certs'  \` starts with a double slash which gets a 404/not found resource. Fixed this by removing the extra slash

Removed extra slash in URI

---

content/nginxaas-azure/changelog.md
content/nginxaas-azure/faq.md
content/nginxaas-azure/known-issues.md

This PR fixes the URLs for the Changelog, Known Issues, and FAQ topics.
The **Known Issues**, **Changelog**, and **FAQ** pages for **NGINXaaS for Azure** have URLs that don’t follow the standard format used for other NGINXaaS for Azure (N4A) docs:
- [https://docs.nginx.com/nginxaas-azure/faq/](https://docs.nginx.com/nginxaas-azure/faq/)
- [https://docs.nginx.com/nginxaas-azure/changelog/](https://docs.nginx.com/nginxaas-azure/changelog/)
- [https://docs.nginx.com/nginxaas-azure/known-issues/](https://docs.nginx.com/nginxaas-azure/known-issues/)
The URLs should follow the correct structure:
`https://docs.nginx.com/nginxaas/azure/…/`

specified the correct URL for known issues, faq, and changelog

---

content/includes/security/rbac-intro.md
content/nginx-one/rbac/_index.md
content/nginx-one/rbac/overview.md
content/nginx-one/rbac/rbac-api.md
content/nginx-one/rbac/roles.md
content/nim/admin-guide/rbac/overview-rbac.md

Problem: Describe existing XC features usable for RBAC for NGINX One Console
Solution: Organize content as drafted by PM
Note how this PR organizes the drafted content, under "Role-based access control"
When you review the "[build](https://frontdoor-test-docs.nginx.com/previews/docs/248/nginx-one)" review the content in the ToC, under "Role-based access control".
Closes #209 

feature: Describe use of XC-based RBAC

---

content/ngf/how-to/monitoring/prometheus.md
static/ngf/ngf-grafana-dashboard.json

Update documentation on prometheus metrics.
Problem: Because NGF now uses NGINX Agent to export NGINX metrics, we need to update our documentation on metrics available and the example grafana dashboard.
Solution: Update the metrics.
Testing: Ran `make watch` and it looks good.
- [x ] I have read the [contributing guidelines](https://github.com/nginx/documentation/blob/main/CONTRIBUTING.md)
[^1]: Potentially sensitive changes include anything involving code, personally identify information (PII), live URLs or significant amounts of new or revised documentation. Please refer to [our style guide](https://github.com/nginx/documentation/blob/main/templates/style-guide.md) for guidance about placeholder …

Update NGF documentation on prometheus metrics

---

content/nginxaas-azure/billing/overview.md
content/nginxaas-azure/changelog.md
content/nginxaas-azure/getting-started/nginx-configuration/overview.md
content/nginxaas-azure/monitoring/metrics-catalog.md
content/nginxaas-azure/overview/overview.md
content/nginxaas-azure/quickstart/scaling.md

Now that we have the Standard plan officially
retired, we should update our docs with the same
information and point users to migrate over to it.
If this PR addresses an [issue](https://github.com/nginx/documentation/issues) on GitHub, ensure that you link …

Update docs to point towards Standard V2

---

.github/labeler.yml
.github/workflows/labeler.yml

Adds a labeler action that adds labels automatically to new PRs based on the rules in the labeler.yml file

feat: add labeler action

---

content/nginx/deployment-guides/amazon-web-services/route-53-global-server-load-balancing.md

This PR:
- Unpublishes and de-indexes the [Global Server Load Balancing with Amazon Route 53 and NGINX Plus](https://docs.nginx.com/nginx/deployment-guides/amazon-web-services/route-53-global-server-load-balancing/) guide.
Issues:
- The guide has 18 broken images and needs a complete overhaul. 
- Views for the guide have dropped from 1402 a year ago to 215 now (an 85% decline), with most views lasting between 0-1 second.

Unpublished Global Server Load Balancing with Amazon Route 53 and NGINX Plus

---

content/includes/nap-waf/config/common/anti-automation.md

This commit removes the link to the Yioop search engine, which is currently offline. Our pipeline automatically checks for broken links, and has been firing warnings about this.
By changing the link to plain text, readers still retain the context that the associated bot is trusted.

feat: Remove broken link to Yioop search engine

---

content/nap-dos/deployment-guide/learn-about-deployment.md

Add extra information for the app protect dos eBPF manager

feat: Update docs -  with overview for App Protect DoS eBPF manager

---

content/includes/nginx-plus/install/copy-jwt-to-etc-nginx-dir.md
content/nginx/admin-guide/installing-nginx/installing-nginx-open-source.md
content/nginx/admin-guide/installing-nginx/installing-nginx-plus.md

Hi,
Patch 1 updates software versions in 'Installing NGINX Open Source'
Patch 2 updates the "Unprivileged installation" section to align with the latest script update
Patch 3 fixes the JWT add procedure: there's no need to create /etc/nginx/ as it is created automatically during installation
Thanks!

Minor updates for NGINX OSS and Plus installation guides.

---

content/nap-waf/v4/releases/about-4.14.md
content/nap-waf/v5/releases/about-5.6.md

Closes #ISSUE
[^1]: Potentially sensitive changes …

feat: Add placeholders for NAP 5.6 / 4.14 release notes

---

CONTRIBUTING_DOCS.md

Update `CONTRIBUTING_DOCS.md` for new usage of `call-out` shortcode. See below for output:
Before:
After:

Update call-out shortcode usage in Contributing

---

content/nginxaas-azure/changelog.md
content/nginxaas-azure/monitoring/metrics-catalog.md
content/nginxaas-azure/quickstart/scaling.md

Problem: The NGINXaaS project is phasing out the old consumed NCUs metric and replacing it with the new, more accurate, percentage capacity metric.
Solution: We are informing users of the change, urging them to make use of the new percentage capacity metric and modifying our guidance about scaling to reflect the change. 

NLB-5919 Inform users of the new nginxaas.capacity.percentage metric

---

content/nginx-one/rbac/rbac-api.md
content/nginx-one/rbac/roles.md

Problem: Inaccuracies and confusing sentences in new RBAC docs for N1.
Solution: Reworded and revised for accuracy.
Testing: N/A
Please focus on (optional): N/A

Update and clarify NGINX One RBAC docs

---

content/ngf/how-to/traffic-security/integrating-cert-manager.md

cert-manager has updated their installation command, so we need to update our docs to reflect that change.

Update NGF cert-manager docs

---

content/ngf/how-to/data-plane-configuration.md

A header link was not written correctly and didn't actually link to the section.

Fix NGF header link

---

content/nim/nginx-app-protect/security-monitoring/_index.md
content/nim/nginx-app-protect/security-monitoring/set-up-app-protect-instances.md
content/nim/nginx-app-protect/security-monitoring/troubleshooting.md
content/nim/nginx-app-protect/security-monitoring/update-geo-db.md
content/nim/nginx-app-protect/security-monitoring/update-signatures.md
content/nim/nginx-app-protect/setup-waf-config-management.md

This commit updates the Security Monitoring subsection of the NAP WAF documentation within NGINX Instance Manager to have contemporary frontmatter formatting, including a fixed url parameter for the index.
The previous URL parameter was causing some odd behaviour, with duplicate deployments of folders.

feat: Update NIM Security Monitoring front matter and reference links

---

content/agent/installation-upgrade/installation-unprivileged.md

As a user,
I want clear documentation on how to run the NGINX Agent as a non-root user,
so that I can adhere to security best practices.
Solution: A new page is required which details how to install the NGINX Agent in non-root mode

docs: add agent unprivileged doc

---

content/nap-dos/deployment-guide/learn-about-deployment.md
content/nap-dos/releases/about-4.6.md

Changes for App Protect Dos 4.6 release over Nginx Plus R34 to include following content
- Compliance with Nginx Plus R34
- NAP-Dos Support AmazonLinux 2023
- NAP-DoS Deprecate Alpine 3.17
- Telemetry Readiness
- Bug fixes.
Testing:  using Hugo 
```
usr/local/bin/hugo --bind 0.0.0.0 -p 1313 server --disableFastRender
```
Closes 
[BADOS-1659](https://jira.f5net.com/browse/BADOS-1659)
[BADOS-1709]( https://jira.f5net.com/browse/BADOS-1709)
[^1]: Potentially sensitive changes include anything involving code, personally identify information (PII), live URLs or significant amounts of new …

Raanan dos release 4.6

---

content/nap-dos/deployment-guide/learn-about-deployment.md
content/nap-dos/releases/about-4.6.md

set "" instead of "service"
For debian/ubuntu instruction fix from "service nginx start" to correct "systemctl start nginx"

fix "debian/ubuntu instruction" for service

---

content/nginx/admin-guide/web-server/reverse-proxy.md

Problem: A user had reported that the content was hard to read through a Qualtrics survey.
Solution: The content was summarized and split into bullet points where possible in order to make it more digestible and easier to read for non-native English speakers.
This PR addresses [Issue - reportedly difficult to read](https://github.com/nginx/documentation/issues/299)

Improve readability of NGINX reverse proxy doc (#299)

---

CLOSED_CONTRIBUTIONS.md
F5-NGINX-team-notes.md

This commit adds a new document to explain the closed contribution process. As part of the changes, related content is updated from the existing documentation specific to F5 employees, decoupling this particular use case from general guidance.
At a future point, both documents may be reorganised into alternate files as part of peripheral efforts to document ways of working.

feat: Add closed contribution process

---

content/nim/nginx-app-protect/setup-waf-config-management.md

Created few custom policies having 'modifications block' with various 'entityTypes'. Able to apply these policies to datapath instances in NIM. Hence removing this limitation.
Problem:  The  limitation ' Policies with modifications' has been present in NIM documentation. 
Solution: This limitation needs to be removed from the docs as it is not valid anymore.
Testing: Created few custom policies having 'modifications block' with various 'entityTypes'. Able to apply these policies to datapath instances in NIM. Hence removing this limitation.
Closes #ISSUE
[^1]: Potentially sensitive …

Remove the limitation 'Policies with modifications' in NIM

---

CLOSED_CONTRIBUTIONS.md

This pull request updates the closed documentation contribution process by fixing the remote git command, and grouping the relevant a user would likely do in quick succession. 
It also rephrases it on the premise that the user likely already has the main repository cloned, so gives and frames adding the remote as an earlier step in the process overall.
The process itself was used to make this pull request!
[^1]: Potentially sensitive changes include anything involving code, personally identify information (PII), live URLs or significant amounts of new or revised documentation. Please refer to [our style guide](https://github.com/nginx/documentation/blob/main/templates/style-guide.md) for guidance about …

feat: Update closed documentation process

---

content/nginx-one/how-to/staged-configs/add-staged-config.md
content/nginx-one/how-to/staged-configs/api-staged-config.md

fix: typos

---

content/agent/about.md
content/agent/how-to/configuration-overview.md
content/agent/install-upgrade/install.md
content/agent/install-upgrade/migrate-v3.md
content/agent/otel/configure-otel-metrics.md
content/agent/technical-specifications.md
content/agent/troubleshooting.md
go.mod
go.sum

- Initial commit of v3 docs.
Closes #ISSUE
[^1]: …

docs:Adding agent v3 docs

---

content/ngf/how-to/traffic-security/securing-backend-traffic.md
content/ngf/overview/gateway-api-compatibility.md

NGF now supports the ability to configure a BackendTLSPolicy with a Secret containing the CA certificate.
https://github.com/nginx/nginx-gateway-fabric/issues/3121

NGF: Secret support for BackendTLSPolicy

---

CLOSED_CONTRIBUTIONS.md

Thanks to some follow up work by @eepifanova, we can now target the main branch for closed content work. This commit updates the documentation to reference the main branch, and also adds specificity of origin and remote when referencing it for clarity.
It also adds missing punctuation, and adjusts spacing in an early paragraph using a line break.

feat: Update closed contribution documentation with new branch

---

content/nginx-one/changelog.md

Problem: Added changelog entry for already existing documentation for granular API groups in NGINX one.
Solution: N/A
Closes #ISSUE
[^1]: Potentially sensitive changes include anything involving code, personally identify information (PII), live URLs or …

Added documentation for granular API groups feature in NGINX One

---

content/nim/admin-guide/license/report-usage-connected-deployment.md
content/nim/deploy/vm-bare-metal/install-nim-deprecated.md
content/nim/disconnected/report-usage-disconnected-deployment.md
content/nim/system-configuration/secure-traffic.md
content/nms/acm/tutorials/aws-deploy.md
content/solutions/about-subscription-licenses.md

Typo fixed

---

content/nginx/admin-guide/dynamic-modules/opentelemetry.md

This is a big update of OpenTelemetry dynamic module page.
- new intro
- added prerequisites
- added sudo and dnf update
- updated linux commands to be copy-pasteable
- refactored linux commands to look more friendly
- removed unneeded duplication of reference as the official module docs are on nginx.org
- added descriptions for examples
- removed unneeded html (spans)
- tested with Ubuntu and FreeBSD
[^1]: Potentially sensitive changes include anything involving code, personally identify information (PII), live URLs or significant amounts of new or revised documentation. Please refer to [our style guide](https://github.com/nginx/documentation/blob/main/templates/style-guide.md) for guidance about …

Updated OpenTelemetry Dynamic module.

---

content/nginx/admin-guide/dynamic-modules/brotli.md
content/nginx/admin-guide/dynamic-modules/cookie-flag.md
content/nginx/admin-guide/dynamic-modules/dynamic-modules.md
content/nginx/admin-guide/dynamic-modules/encrypted-session.md
content/nginx/admin-guide/dynamic-modules/fips.md
content/nginx/admin-guide/dynamic-modules/geoip.md
content/nginx/admin-guide/dynamic-modules/geoip2.md
content/nginx/admin-guide/dynamic-modules/headers-more.md
content/nginx/admin-guide/dynamic-modules/http-substitutions-filter.md
content/nginx/admin-guide/dynamic-modules/image-filter.md
content/nginx/admin-guide/dynamic-modules/lua.md
content/nginx/admin-guide/dynamic-modules/ndk.md
content/nginx/admin-guide/dynamic-modules/nginscript.md
content/nginx/admin-guide/dynamic-modules/nginx-waf.md
content/nginx/admin-guide/dynamic-modules/opentracing.md
content/nginx/admin-guide/dynamic-modules/passenger-open-source.md
content/nginx/admin-guide/dynamic-modules/perl.md
content/nginx/admin-guide/dynamic-modules/prometheus-njs.md
content/nginx/admin-guide/dynamic-modules/rtmp.md
content/nginx/admin-guide/dynamic-modules/set-misc.md
content/nginx/admin-guide/dynamic-modules/spnego.md
content/nginx/admin-guide/dynamic-modules/uninstall.md
content/nginx/admin-guide/dynamic-modules/xslt.md

This patch:
- adds sudo to installation commands
- adds a command for repo update
- adds a url to "Uninstalling a dynamic module"
- removes extra line breaks
- removes most of span tags in Dynamic modules

Updated installation commands in Dynamic Modules.

---

content/nginx/releases.md

This PR updates the Software Development Policy and clarifies the End of Software Development (EoSD) for NGINX Plus releases.
Tested locally with Hugo and Docker.

Updated Software Development Policy in Releases.

---

content/includes/nap-waf/bundles-volume-mount.md
content/nap-waf/v5/admin-guide/deploy-on-docker.md

Fixed a wrong syslog port, added commands to list available NAPv5 image tags

Bugfix on syslog port, added commands to list available NAPv5 images

---

content/nginxaas-azure/changelog.md
content/nginxaas-azure/faq.md

NLB-6321: Notification on R33 release

---

content/controller/releases/apim/apim-release-notes-3.19.2.md
content/nginxaas-azure/known-issues.md

Closes https://github.com/nginxinc/docs-platform/issues/463

 Refactor highlight shortcode to use ticks

---

content/nap-dos/deployment-guide/installing-nginx-plus-with-dos-and-waf-on-amazon-web-services.md
content/nginx/admin-guide/monitoring/live-activity-monitoring.md

Problem: Remove the Gerund form from the Headings.
Solution: Replaced it with an imperative verb. Also removed the article before the product name.
Testing: NA. Did a preview of the page.
If this PR addresses an [issue](https://github.com/nginx/documentation/issues) on GitHub, ensure that you link to it here: https://github.com/nginx/documentation/issues/396
Closes #ISSUE
[^1]: Potentially sensitive changes include …

Avoid Gerund #396

---

content/includes/use-cases/monitoring/enable-nginx-plus-api.md
content/nginx-one/getting-started.md

The change in this PR is "simpler than it looks", as we had set up variables to include the same content for N+ as we do for NIM
So I link to the production doc section, and the proposed change with the build:
- [Current doc](https://docs.nginx.com/nginx-one/getting-started/#enable-nginx-metrics-reporting)
- [Change with PR](https://frontdoor-test-docs.nginx.com/previews/docs/426/nginx-one/getting-started/#enable-nginx-metrics-reporting)
Based on feedback. Short version, the words in our current doc suggest more metrics than we deliver.
Doc note: as this is _currently_ based on common content with https://docs.nginx.com/nginx-instance-manager/monitoring/overview-metrics/#f5-nginx-plus-metrics, I have disabled the "include" functionality that (essentially) copies that content.
Before …

fix: minimize reference to metrics

---

content/includes/nim/tech-specs/nim-app-protect-support.md
content/nim/nginx-app-protect/setup-waf-config-management.md

Updated the compatibility matrices in Technical Specifications for NGINX App Protect Releases 4.14.0 and 5.6.0. Also updated the nms-nap-compiler versions that correspond to those NAP releases.
Testing: Tested Locally.
Closes #ISSUE …

docs: update the NAP and NIM versions for NAP 4.14.0 and 5.6.0

---

content/ngf/how-to/traffic-management/mirror.md
content/ngf/overview/gateway-api-compatibility.md

NGF is adding the capability for users to configure request mirroring. This adds a guide explaining how a user can set this up.
Issue: https://github.com/nginx/nginx-gateway-fabric/issues/533

Add NGF request mirror doc

---

CONTRIBUTING_DOCS.md

This commit updates the CONTRIBUTING_DOCS.md file to our contemporary standards for documentation formatting, adding mention of Hugo archetypes and our ghcode shortcode, while also removing some slightly redundant information.
Certain sentences have been removed or simplified to reduce the amount of contextual reading required: in certain cases, the reader is guided to refer to the style guide for more precise information, such as in the case of using images.
There will likely be follow-up work in the future to more cleanly delineate guidance for using Hugo and guidance around writing content in a general sense, to tightly scope the purpose of this document in relation to the style guide.
Closes issue #164 
Before merging a pull request, run through this checklist and mark each as …

feat: Update Contributing guidelines for writers

---

content/ngf/overview/custom-policies.md
content/ngf/overview/product-telemetry.md

UpstreamSettingsPolicy was missing from the custom policies table.
Add this to the table, and fix a formatting error in the product telemetry doc.

NGF: Update custom policies table

---

layouts/index.html

See matching theme PR for screenshots - https://github.com/nginxinc/nginx-hugo-theme/pull/234
This should have no impact on oldframe.
**Use this preview link - https://frontdoor-test-docs.nginx.com/previews/docs/8de07aa/**

Homepage: Add basic mainframe home page

---

layouts/index.html

Homepage: Fix nginxaas and unit links

Homepage: Fix nginxaas and unit links

---

content/nginx-one/changelog.md

Reverts nginx/documentation#434
Nginx One production fix is blocked on staging failure. Best to not show changelog until that's resolved

Revert "Updated change log for namespace release"

---

archetypes/concept.md
archetypes/default.md
archetypes/tutorial.md

To reduce name collisions and make it explicitly clear which frontmatter fields are used by DocOps (As opposed to native Hugo fields which interact with specific mechanisms), this PR adds an `nd` prefix.
This ensures that documents generated using `hugo new` will have the correct fields in the future. Follow up work to update existing fields and documents will be handled in other pull requests.
[^1]: Potentially sensitive changes include anything involving code, personally identify information (PII), live URLs or significant amounts of new or revised documentation. Please refer to [our style guide](https://github.com/nginx/documentation/blob/main/templates/style-guide.md) for guidance about placeholder …

feat: Add prefix to custom frontmatter in Hugo archetypes

---

content/ngf/how-to/monitoring/dashboard.md
content/ngf/how-to/monitoring/tracing.md
content/ngf/how-to/monitoring/troubleshooting.md
content/ngf/how-to/traffic-management/advanced-routing.md
content/ngf/how-to/traffic-management/client-settings.md
content/ngf/how-to/traffic-management/https-termination.md
content/ngf/how-to/traffic-management/mirror.md
content/ngf/how-to/traffic-management/redirects-and-rewrites.md
content/ngf/how-to/traffic-management/request-response-headers.md
content/ngf/how-to/traffic-management/routing-traffic-to-your-app.md
content/ngf/how-to/traffic-management/snippets.md
content/ngf/how-to/traffic-management/tls-passthrough.md
content/ngf/how-to/traffic-management/upstream-settings.md
content/ngf/how-to/traffic-security/integrating-cert-manager.md
content/ngf/how-to/traffic-security/securing-backend-traffic.md
content/ngf/installation/installing-ngf/manifests.md
content/ngf/overview/nginx-plus.md

Update documentation on accessing nginx container
Problem: With our incoming changes to our control data plane split, the nginx container will no longer be in the NGF Pod. Thus all documentation on accessing the nginx container (logs, sending traffic, config...) need to be updated.
Solution: Updated the documentation. Mainly, when sending traffic in the examples, the host and IP of the NGINX Service are recorded after the Gateway is deployed. Also updated a link in the NGINX Plus feature document to point away from the NGINX Prometheus exporter and to the internal document showing metrics.
Testing: Ran `make watch` and it looked good.
Closes 
[^1]: Potentially sensitive changes include anything involving …

NGF: Update documentation on accessing nginx container

---

content/nim/nginx-app-protect/setup-waf-config-management.md

Fixed broken anchor in link

---

content/ngf/get-started.md

The getting started guide needs to change with the new NGF architecture, specifically regarding the NodePorts. The user no longer needs to create the Service, and instead specifies configuration at installation time.
Related: https://github.com/nginx/nginx-gateway-fabric/issues/3240
[^1]: Potentially sensitive changes include anything involving code, personally identify information (PII), live URLs or significant amounts of new or revised documentation. Please refer to [our style guide](https://github.com/nginx/documentation/blob/main/templates/style-guide.md) for guidance about …

NGF: update Get started guide

---

content/includes/licensing-and-reporting/apply-jwt.md
content/includes/licensing-and-reporting/configure-nginx-plus-report-to-nim.md
content/solutions/about-subscription-licenses.md

This PR:
- Adds a step to reload NGINX after applying the JWT

Added step to reload NGINX after adding JWT

---

content/nginx/admin-guide/web-server/app-gateway-uwsgi-django.md

Problem: Article is listed as "difficult" to read.
Solution: Use Hemingway App to drop readability score from 10 to 9. Fleisch Kinkaid estimate from 14.46 to 8.2.
If this PR addresses an [issue](https://github.com/nginx/documentation/issues) on GitHub, ensure that you link to it here: https://github.com/nginx/documentation/issues/359
Closes Issue #359

Simplify readability for NGINX Plus Admin Guide: Gateway with uWSGI and Django

---

content/nginx/admin-guide/security-controls/securing-tcp-traffic-upstream.md

style: improve readability and streamline language
The article was originally difficult to read, with a high grade level (12). The writing was wordy and conversational, and contained long sentences covering too many topics. 
The proposed changes make the writing more direct and "punchy" while breaking up long, complex sentences.
Closes #ISSUE [363](https://github.com/nginx/documentation/issues/363)
- [n/a] If the change involves potentially sensitive changes[^1], I have assessed the possible impact
- [n/a] If applicable, I have added tests that prove my fix is effective or that my feature works
- [n/a] I have ensured that existing tests pass after adding my changes
[^1]: Potentially sensitive changes …

Improve the article's readability; streamline the language.

---

content/nginx/admin-guide/security-controls/securing-http-traffic-upstream.md

Problem: The page contained many long sentences and clauses that could be simplified to enhance readability.
Solution: I split up longer sentences into smaller sentences, and I also changed a list separated by commas into bullet points.
Testing: N/A
Please focus on (optional): I focused my edits on the top portion of the document except for the bullet point section toward the end of the document. 
Closes #361 
[^1]: Potentially sensitive changes include anything involving code, personally identify information (PII), live URLs or significant amounts of new or revised documentation. …

361 httptraffic

---

content/nginx/admin-guide/security-controls/configuring-subrequest-authentication.md

Problem: Introduction is not written clearly.
Solution: Separated multiple lines into bullets and made small wording changes throughout
Testing: None
Closes #ISSUE
[^1]: Potentially sensitive changes include anything involving code, personally identify information (PII), live URLs or significant …

edit to introduction, add new response codes section

---

content/nginxaas-azure/quickstart/runtime-state-sharing.md

This is related to https://github.com/nginx/documentation/issues/364.
The docs for Azure Runtime State Sharing is overly complex, this PR attempts to simplify one part of it.
According to https://hemingwayapp.com, the complexity rating has still not decreased overall. But the following improvements have been made:
- Net 4 sentences have been removed from "very hard to read"
- Net 2 sentences have been added as "hard to read" (some were slightly improved from above)
- 2 weakeners have been removed
Many of the "complex" sentences either include many links or use very specific (and long) terms.
[^1]: Potentially sensitive changes include anything involving code, personally identify information (PII), live …

docs: simplifies some of the Runtime State Sharing docs

---

archetypes/concept.md
archetypes/default.md
archetypes/tutorial.md

This commit updates the Hugo archetypes to remove the horizontal lines delineating each section, and also changes the final sections of each section. The future website theme uses meaningful whitespace for breaking sections up instead of horizontal lines, so removing it from the templates prevents more from being added.
"See also" was changed to "Next steps" for two of the archetypes, with more specific examples for all three. This reflects discussions around the fact that "See also" doesn't inspire informed content design.
"Next steps" is more appropriate for specific use cases, especially with the context of the working document - we have a good idea of what the reader may need to do next, so the title should reflect that.
Before merging a pull request, run through this checklist and …

feat: Update Hugo archetypes to remove HRs and change final subsection

---

content/ngf/how-to/traffic-security/integrating-cert-manager.md
content/ngf/installation/installing-ngf/control-plane-certs.md
content/ngf/installation/installing-ngf/helm.md
content/ngf/installation/installing-ngf/manifests.md

With the control plane and data plane split in NGF, a secure connection is necessary for communication between the two entities. We secure this by default, but for production environments, users should use an official solution to secure this communication channel. This doc describes how to do that.
Related https://github.com/nginx/nginx-gateway-fabric/issues/3236

NGF: add control plane/data plane TLS doc

---

content/ngf/how-to/data-plane-configuration.md

Data plane configuration doc needs to be updated to reflect new changes in NginxProxy resource
Closes #ISSUE
https://github.com/nginx/nginx-gateway-fabric/issues/3238
[^1]: Potentially sensitive changes include anything involving code, personally identify …

NGF: Update data plane configuration doc

---

content/ngf/how-to/scaling.md
content/ngf/how-to/upgrade-apps-without-downtime.md

Problem: Users need a how to guide on how to scale control plane and data plane
Solution: Introduces a new `how-to` guide on scaling control and data plane pods 
https://github.com/nginx/nginx-gateway-fabric/issues/3235
Closes #ISSUE
[^1]: Potentially …

NGF: Scaling control plane and data plane pods

---

content/nginxaas-azure/changelog-archive/changelog-2024.md
content/nginxaas-azure/changelog.md
content/nginxaas-azure/loadbalancer-kubernetes.md

Moves the NGINXaaS for Azure Load balancer topic to the root of the docs.
- Fix link dependencies related to the move

docs: move n4a load balancer topic

---

content/ngf/installation/installing-ngf/manifests.md

There is no longer an aws-nlb deploy.yaml file, so we need to update the manifests installation and give some information on setting annotations in the Gateway.
Problem: There is no longer an aws-nlb deploy.yaml file, so we need to update documentation.
Solution: Update the documentation and give information on setting annotations on the Gateway.
Testing: Checked with `make watch`
Related with: https://github.com/nginx/nginx-gateway-fabric/pull/3362
Closes  …

Update aws nlb manifests installation

---

content/nginx-one/how-to/staged-configs/add-staged-config.md

This commit fixes a typo in the main body text of the documentation, and also updates the Hugo frontmatter to new parameter names and values.

fix: Address typo update metadata for Add a Staged Configuration topic

---

content/nginx/admin-guide/web-server/app-gateway-uwsgi-django.md

This PR corrects the example description and example ident introduced in https://github.com/nginx/documentation/pull/518, also minor update of uwsgi sample command (adding the 'uwsgi' command itself as we're referring to it later)

Updated example description for uwsgi and Django.

---

content/nginx/deployment-guides/load-balance-third-party/wildfly.md

This PR fixes the link to Dynamic modules in https://docs.nginx.com/nginx/deployment-guides/load-balance-third-party/wildfly/#configuring-http2-support
Closes an internal issue

Fixed URL to dynamic modules for Wildfly deployment guide.

---

content/ngf/how-to/monitoring/tracing.md
content/ngf/installation/installing-ngf/helm.md

Problem: Some of the instructions relating to Helm values haven't been updated to reflect the changes from the CP/DP split
Solution: Updated the tracing and Helm install docs in this respect
Closes https://github.com/nginx/nginx-gateway-fabric/issues/3243

NGF: Update Helm values where required for 2.0

---

content/includes/agent/installation/manually-connect-to-console.md
go.mod
go.sum

- Added detail on how to check if agent is installed
- Changed `sudo systemctl stop nginx-agent` to `sudo systemctl restart nginx-agent` as described in the text above
- Added a link to setting up NGINX One Console after agent has been installed

Update agent install docs

---

content/nginx-one/changelog.md
content/nginx-one/how-to/staged-configs/api-staged-config.md
content/nginx-one/how-to/staged-configs/import-export-staged-config.md
static/nginx-one/api/one.json

**NOTE** Approved. Hold for release on Monday May 19.
Adds content / API docs for Staged Configs, specifically functionality to:
- Import
- Export
- Bulk manage several Staged Configs
Also includes corresponding API content from https://github.com/nginx/documentation/pull/489, cc @vivki 
- I've added that so I can test links from https://frontdoor-test-docs.nginx.com/previews/docs/553/nginx-one/how-to/staged-configs/api-staged-config/
- Unfortunately, the link from https://frontdoor-test-docs.nginx.com/previews/docs/553/nginx-one/api/api-reference-guide/#operation/exportStagedConfig to https://docs.nginx.com/nginx-one/how-to/staged-configs/import-export-staged-config/ won't work until the changes are published. (long explanation, I'm happy to explain to anyone)
Closes #ISSUE
Before …

feature: Add import, export, bulk management of Staged Configs

---

content/ngf/how-to/monitoring/prometheus.md

Agent updated some metrics names and descriptions. Updating the NGF doc that describes them.

NGF: update nginx metrics

---

content/ngf/installation/installing-ngf/deploy-data-plane.md
content/ngf/installation/installing-ngf/manifests.md

Add "Deploy Data plane document" to guide users on how to create and modify the NGINX Data Plane.
Problem: Users want a guide on how to create and modify the NGINX Data Plane.
Solution: Added the guide.
Testing: Tested with `make watch`
Closes https://github.com/nginx/nginx-gateway-fabric/issues/3237

NGF: Add Deploy data plane doc

---

content/ngf/overview/gateway-api-compatibility.md

Updates Gateway Compatibility document to reflect new architecture changes.
Closes #ISSUE
[Gateway Compatibility Updates for 2.0](https://github.com/nginx/nginx-gateway-fabric/issues/3239) …

NGF: Update Gateway Compatibility Document

---

static/nginx-one/api/one.json

Closes #ISSUE
[^1]: Potentially sensitive changes …

add docs for staged configs phase 2

---

content/ngf/installation/installing-ngf/helm.md

Problem: The image pull secret values instructions for installing Plus using Helm are incorrect 
Solution: Update these from `serviceAccount.imagePullSecret` to `nginx.imagePullSecret`

NGF: Update missed imagePullSecret helm values

---

content/nginxaas-azure/changelog.md

From 05 May 2025 to 09 May 2025, NGINXaaS deployment running on the [Stable Upgrade Channel](https://docs.nginx.com/nginxaas/azure/quickstart/upgrade-channels/) will be updated to [NGINX Plus Release 33 (R33)](https://docs.nginx.com/nginx/releases/#nginxplusrelease-33-r33). 
Closes #ISSUE

NLB-6321: R33 release announcement 

---

content/ngf/support.md

The repo was migrated from nginxinc to nginx organization.

Update supportpkg link for NGF

---

.github/workflows/build-push.yml

This adds support for `/`'s in branch names, to trigger build and deploys from PRs.

Tooling: Pull request triggers support slashes in branch names

---

content/nginx/admin-guide/basic-functionality/runtime-control.md

Problem: basic English word
Solution: fixes the typo
Testing: I read the sentence like nobody else would
Please focus on (optional): grammar xd
- [-] If the change involves potentially sensitive changes[^1], I have assessed the possible impact
- [-] If applicable, I have added tests that prove my fix is effective or that my feature works
- [-] I have ensured that existing tests pass after adding my changes
- [-] If applicable, I have updated [`README.md`](https://github.com/nginx/documentation/blob/main/README.md) and [`CHANGELOG.md`](https://github.com/nginx/documentation/blob/main/CHANGELOG.md)
[^1]: Potentially sensitive changes include anything involving code, personally identify information (PII), …

fix: control nginx docs typo

---

content/includes/nginx-one/staged-config-overview.md
content/nginx-one/changelog.md
content/nginx-one/rbac/rbac-api.md

As stated in title. Note, we currently see "AI Assistant" and/or "NGINX AI Assistant" in the following locations:
- https://docs.nginx.com/nginx-one/how-to/staged-configs/import-export-staged-config/
- https://docs.nginx.com/nginx-one/how-to/staged-configs/edit-staged-config/
- https://docs.nginx.com/nginx-one/how-to/staged-configs/add-staged-config/
- https://docs.nginx.com/nginx-one/rbac/rbac-api/
- https://docs.nginx.com/nginx-one/changelog/
I've changed the first 3 with our "include" file (which includes the same content in the first 3 locations). You can check for yourself by navigating from the build to NGINX One > How-to guides > Staged Configurations
[^1]: Potentially sensitive changes include …

Update name of AI Assistant to F5 AI Assistant

---

content/nginx/admin-guide/installing-nginx/installing-nginx-plus-amazon-web-services.md
content/nginx/admin-guide/monitoring/new-relic-plugin.md
content/nginx/deployment-guides/amazon-web-services/high-availability-keepalived.md
content/nginx/deployment-guides/amazon-web-services/high-availability-network-load-balancer.md
content/nginx/deployment-guides/amazon-web-services/ingress-controller-elastic-kubernetes-services.md
content/nginx/deployment-guides/amazon-web-services/route-53-global-server-load-balancing.md
content/nginx/deployment-guides/global-server-load-balancing/ns1-global-server-load-balancing.md
content/nginx/deployment-guides/google-cloud-platform/high-availability-all-active.md
content/nginx/deployment-guides/load-balance-third-party/apache-tomcat.md
content/nginx/deployment-guides/load-balance-third-party/microsoft-exchange.md
content/nginx/deployment-guides/load-balance-third-party/node-js.md
content/nginx/deployment-guides/load-balance-third-party/oracle-e-business-suite.md
content/nginx/deployment-guides/load-balance-third-party/oracle-weblogic-server.md
content/nginx/deployment-guides/load-balance-third-party/wildfly.md
content/nginx/deployment-guides/microsoft-azure/high-availability-standard-load-balancer.md
content/nginx/deployment-guides/microsoft-azure/virtual-machines-for-nginx.md
content/nginx/deployment-guides/migrate-hardware-adc/citrix-adc-configuration.md
content/nginx/deployment-guides/migrate-hardware-adc/f5-big-ip-configuration.md
content/nginx/deployment-guides/nginx-plus-high-availability-chef.md
content/nginx/deployment-guides/setting-up-nginx-demo-environment.md
content/nginx/deployment-guides/single-sign-on/oidc-njs/active-directory-federation-services.md
content/nginx/deployment-guides/single-sign-on/oidc-njs/cognito.md
content/nginx/deployment-guides/single-sign-on/oidc-njs/keycloak.md
content/nginx/deployment-guides/single-sign-on/oidc-njs/onelogin.md
content/nginx/deployment-guides/single-sign-on/oidc-njs/ping-identity.md

This PR removes `<span>` tags that were used for bolding and non-breaking spaces and hyphens -- and replaces them with standard Markdown formatting.

replaced span styles with markdown

---

content/nginx/deployment-guides/single-sign-on/oidc-njs/keycloak.md

Fixed outdated .well-known URL, the fix works with Keycloak 26.2

Fixed Keycloak .well-known URL

---

content/ngf/installation/installing-ngf/helm.md
content/ngf/installation/installing-ngf/manifests.md

Adds upgrade document link to NGF installation documents.
Closes #ISSUE

NGF: Update installation document with 2.x upgrade information

---

templates/style-guide.md

Always use "F5 AI Assistant", as directed by PM management.

Update style-guide.md for AI Chatbots

---

content/nginx-one/how-to/certificates/manage-certificates.md
content/nginx-one/how-to/config-sync-groups/manage-config-sync-groups.md

Based on feeback. 
We need to clarify: N1C collects _only_ the metadata associated with unmanaged certs. IOW, it does not include the actual cert.

fix: unmanaged certs only include metadata

---

content/nginx-one/how-to/staged-configs/import-export-staged-config.md

Correct mistake identified in internal discussion

Fix inaccurate statement

---

content/nginx/admin-guide/installing-nginx/installing-nginx-plus-amazon-web-services.md
content/nginx/admin-guide/monitoring/new-relic-plugin.md
content/nginx/deployment-guides/amazon-web-services/high-availability-keepalived.md
content/nginx/deployment-guides/amazon-web-services/high-availability-network-load-balancer.md
content/nginx/deployment-guides/amazon-web-services/ingress-controller-elastic-kubernetes-services.md
content/nginx/deployment-guides/amazon-web-services/route-53-global-server-load-balancing.md
content/nginx/deployment-guides/global-server-load-balancing/ns1-global-server-load-balancing.md
content/nginx/deployment-guides/google-cloud-platform/high-availability-all-active.md
content/nginx/deployment-guides/load-balance-third-party/apache-tomcat.md
content/nginx/deployment-guides/load-balance-third-party/microsoft-exchange.md
content/nginx/deployment-guides/load-balance-third-party/node-js.md
content/nginx/deployment-guides/load-balance-third-party/oracle-e-business-suite.md
content/nginx/deployment-guides/load-balance-third-party/oracle-weblogic-server.md
content/nginx/deployment-guides/load-balance-third-party/wildfly.md
content/nginx/deployment-guides/microsoft-azure/high-availability-standard-load-balancer.md
content/nginx/deployment-guides/microsoft-azure/virtual-machines-for-nginx.md
content/nginx/deployment-guides/migrate-hardware-adc/citrix-adc-configuration.md
content/nginx/deployment-guides/migrate-hardware-adc/f5-big-ip-configuration.md
content/nginx/deployment-guides/nginx-plus-high-availability-chef.md
content/nginx/deployment-guides/setting-up-nginx-demo-environment.md
content/nginx/deployment-guides/single-sign-on/oidc-njs/active-directory-federation-services.md
content/nginx/deployment-guides/single-sign-on/oidc-njs/cognito.md
content/nginx/deployment-guides/single-sign-on/oidc-njs/keycloak.md
content/nginx/deployment-guides/single-sign-on/oidc-njs/onelogin.md
content/nginx/deployment-guides/single-sign-on/oidc-njs/ping-identity.md
go.mod
go.sum

This PR adds the non-breaking shortcode `{{<nb>}}` as a replacement for `&nbsp;` and `&#8209;`

applied nb shortcode for non-breaking spaces and hyphens

---

content/includes/nim/tech-specs/nim-app-protect-support.md
content/nim/disconnected/offline-install-guide.md

Removed stray '\' and added NIM 2.19.2 to compatibility table

Removed stray '\' and added NIM 2.19.2 to compatibility table

---

content/nginx/fips-compliance-nginx-plus.md

Problem: The cryptographic boundary definition within the 'NGINX Plus FIPS Compliance' document does not include the http_auth_jwt module. This leads to concern that the operational function of the http_auth_jwt module is not fips compliance.
Solution: Add the http_auth_jwt module to the cryptographic boundary definition within the 'NGINX Plus FIPS compliance' document.
Testing: NA
Closes service console case 00857454 - https://f5.lightning.force.com/lightning/r/Case/500Po00000rGPaRIAW/view

Add http_auth_jwt module to cryptographic boundary definition within 'NGINX Plus FIPS Compliance' document

---

_banners/agent-v3-release.md
content/agent/_index.md
content/agent/technical-specifications.md

Add a banner to the agent section of the docs informing users about the release of v3 and links to the upgrade and compatibility section. 
Closes #ISSUE …

Agent info banner

---

content/nginxaas-azure/monitoring/migrate-to-platform-metrics.md

Update new document to follow the style guide:
- Not using sentence case for title
- Inconsistently using Platform Metrics or Platform metrics capitalization, same for Custom Metrics
- Missing blank lines after titles
- Missing F5 on first mention of the product
- "Click"  instead of "Select"
- Extra blank spaces at the end of the lines
- Other markdown issues (blank lines, missing)

style guide corrections to migrate metrics doc

---

content/nginx/admin-guide/load-balancer/http-load-balancer.md
content/nginx/admin-guide/mail-proxy/mail-proxy.md
content/nginx/admin-guide/security-controls/securing-http-traffic-upstream.md
content/nginx/admin-guide/security-controls/securing-tcp-traffic-upstream.md
content/nginx/admin-guide/security-controls/terminating-ssl-http.md
content/nginx/admin-guide/security-controls/terminating-ssl-tcp.md
content/nginx/deployment-guides/load-balance-third-party/microsoft-exchange.md
content/nginx/deployment-guides/migrate-hardware-adc/f5-big-ip-configuration.md
content/nginx/fips-compliance-nginx-plus.md

This PR updates the value of ssl_protocols to default and recommended TLS versions.

Updated the value of ssl_protocols.

---

content/includes/ngf/installation/nginx-plus/docker-registry-secret.md

Fix small link to subsection.
Subsection in question: https://docs.nginx.com/nginx-gateway-fabric/installation/nginx-plus-jwt/#pull-an-image-for-local-use

NGF: Fix small link to subsection

---

static/sitemap_index.xml

Remove external nic sitemap ref. This allows coveo to properly update it's index, now that nic is part of the `documentation` repo.

Remove external nic sitemap ref

---

content/includes/nginx-one/conf/nginx-agent-conf.md
content/nginx-one/agent/containers/run-agent-container.md
content/nginx-one/getting-started.md

I have _not_ checked the steps as this PR describes for the Get started guide.

feature: incorporate nginx-agent.conf 3.0 changes to Get started guide

---

content/includes/config-snippets/enable-nplus-api-dashboard.md
content/includes/use-cases/monitoring/enable-nginx-plus-api.md

This PR:
- Updates the example nginx config snippet for enabling the NGINX API and dashboard.
- Adds the snippet as a standalone include for reuse
- The update includes commented out recommendations for configuring and securing the API
- The snippet includes a link to the related documentation

Updated the config snippet for enabling the NGINX Plus API and dashboard

---

content/nginx-one/_index.md

Resolved N1 landing page links

Resolved n1 landing page links

---

content/includes/nim/kubernetes/access-webui-helm.md
content/includes/nim/kubernetes/nms-chart-supported-module-versions.md
content/nim/deploy/kubernetes/deploy-using-helm.md

- Cleaned up nim chart versions
- `nms`  references changed to `nim`

fix: cleanup of nim charts + minor fixes

---

content/nic/configuration/_index.md
content/nic/installation/_index.md
content/nic/logging-and-monitoring/_index.md
content/nic/overview/_index.md
content/nic/troubleshooting/_index.md

Fix: Root urls in nic need nginx-ingress-controller prefix. This were previously defaulting to `nic` instead of `nginx-ingress-controller`, as it matched the directory name without a specific url.

Fix: Root urls in nic need nginx-ingress-controller prefix

---

content/nginxaas-azure/loadbalancer-kubernetes.md

The added guidance will ensure that users enforce a TLS connection with the dataplane API.

NGINXaaS Load Balancer for Kubernetes configuration update

---

content/nginx-one/connect-instances/connect-nginx-plus-container-images-to-nginx-one.md
content/nginx-one/nginx-configs/config-sync-groups/manage-config-sync-groups.md

Fix broken links from title changes. Identified by @balakoteswar 

Fix broken links

---

content/includes/nim/installation/install-script-flags/distribution.md
content/nim/deploy/vm-bare-metal/install.md
content/nim/disconnected/add-license-disconnected-deployment.md
static/scripts/install-nim-bundle.sh

Problem: 
We have introduced a new option to Nginx Instance Manager Install script to print all the supported operating systems. 
This PR updates the command to print all the supported distributions. 
Removing an extra line when printing the supported operating systems list.
Solution: Updating command 
Closes #ISSUE
[^1]: Potentially sensitive changes include anything involving code, …

fix: updating command to print supported OS list

---

content/nic/installation/installing-nic/installation-with-helm.md

- Add helm documentation for the feature implemented in https://github.com/nginx/kubernetes-ingress/pull/8011
Closes #ISSUE
[^1]: Potentially sensitive changes include anything involving …

feat: adds helm docs for startup probe in NIC

---

content/includes/nap-waf/config/common/nginx-app-protect-waf-terminology.md
content/nginx-one/_index.md
content/nginx-one/changelog.md
content/nginx-one/glossary.md
content/nginx-one/nap-integration/_index.md
content/nginx-one/nap-integration/configure-policy.md
content/nginx-one/nap-integration/deploy-policy.md
content/nginx-one/nap-integration/overview.md
content/nginx-one/nap-integration/review-policy.md
content/nginx-one/nap-integration/security-policy-api.md
static/nginx-one/api/one.json

Content reviewed and approved in an internal mirror of this repository. Based on the procedure described here: https://github.com/nginx/internal-docs/blob/main/documentation/closed-contributions.md
I've essentially mirrored the content here. Once our setup of these repositories is complete, this process will automatically include the approvals given in the internal mirror

Nap usecase stage1

---

content/ngf/overview/gateway-api-compatibility.md

Update gateway api compatibility document for appProtocol changes and percentage-based request mirroring. Merge into unreleased `ngf-release-2.1` branch.

NGF: Update gateway-api compatibility docs

---

content/nginx-one/nginx-configs/config-sync-groups/manage-config-sync-groups.md

Update N1 Config sync steps for Agent 3.x
Closes #ISSUE

docs: update N1 config sync steps for v3

---

content/nginx-one/nginx-configs/config-sync-groups/manage-config-sync-groups.md
documentation/style-guide.md

This PR:
- Adds an Acronyms section to the style guide. This is the list of acronyms that do not need to be spelled out.

Style guide: added list of acronyms that don't need to be spelled out

---

content/nim/nginx-app-protect/setup-waf-config-management.md

Problem: Currently steps of install WAF compiler on disconnected environments is not documented. This PR tries to address it.
Solution: Tested the steps and documented them as part of this PR.
Testing: Tested the steps on Redhat-8, Redhat-9 , Ubuntu-24, Ubuntu-22, oracle-8, oracle-9, debian-11 and debian-12 systems.

fix: Add Offline steps to install WAF compiler on NIM

---

static/nginx-one/api/one.json

Updated NGINX One API doc
Testing: viewed update in hugo server
- [-] I have ensured that documentation content adheres to [the style guide](/documentation/style-guide.md)
- [-] If the change involves potentially sensitive changes[^1], I have assessed the possible impact
- [-] If applicable, I have added tests that prove my fix is effective or that my feature works
- [-] I have ensured that existing tests pass after adding my changes
- [-] If applicable, I have updated [`README.md`](/README.md) …

docs: update nginx-one api doc

---

content/solutions/about-subscription-licenses.md

As reviewed and approved in the private internal repository

Update multiple licenses

---

content/includes/licensing-and-reporting/apply-jwt.md
content/includes/licensing-and-reporting/deploy-jwt-with-csgs.md
content/solutions/about-subscription-licenses.md

This update adds instructions for deploying the JWT license using Config Sync Groups in the NGINX One Console. It also improves the overall structure and clarity of the **About Subscription Licenses** topic by:
- Separating the license download steps into their own H2 section
- Introducing the two deployment workflows (Config Sync Group and manual copy) under a shared H2 with separate H3s
- Leading with the recommended method (Config Sync Group) to highlight the scalable, centralized approach
- Preserving the manual copy method as an alternative for users not using NGINX One
- Adding a callout for users of **NGINX Instance Manager**, noting that instance groups offer similar functionality
- Improve discoverability and clarity of the preferred deployment workflow
- Reduce friction for …

Add JWT license deployment steps for Config Sync Groups; clarify NIM instance group support

---

content/ngf/how-to/data-plane-configuration.md

Problem: NGF is adding a way to submit custom patches to unblock users who need to set fields that are not yet exposed in the NginxProxy CRD. This needs to be documented for users.
Solution: Extend the data plane configuration document to cover this functionality.
Partially addresses https://github.com/nginx/nginx-gateway-fabric/issues/3568
- [] If the change involves potentially sensitive changes[^1], I have assessed the possible impact
[^1]: Potentially sensitive changes include anything involving code, personally identify information (PII), live URLs or significant amounts of new or revised documentation. Please refer to [our style guide](/documentation/style-guide.md) for guidance about placeholder …

NGF: Document patching dataplane Service, Deployment, DaemonSet

---

content/nim/nginx-app-protect/security-monitoring/set-up-app-protect-instances.md

Removed a duplicated `app_protect_enable` directive.

Removed duplicated directive

---

content/nic/releases.md
content/nic/tutorials/security-monitoring.md

- Update 5.1.0 release notes with correct wording,
- Add volumeMount example to manifest installation in security monitoring tutorial
Closes #ISSUE

fix: release notes and update sec monitoring tutorial

---

content/nginx/admin-guide/installing-nginx/installing-nginx-docker.md

As suggested by @alessfg
The docs for building the NGINX Plus Dockerfiles manually found here https://docs.nginx.com/nginx/admin-guide/installing-nginx/installing-nginx-docker#creating-custom-nginx-plus-docker-image need to be updated. Step 3 needs to mention downloading the JWT license in addition to the cert and key. The command in step 5 needs to be updated to:
```
docker build  --no-cache --secret id=nginx-key,src=nginx-repo.key --secret id=nginx-crt,src=nginx-repo.crt --secret id=nginx-jwt,src=license.jwt -t nginxplus .
```
We may have a different problem, as we already cite these three files as prerequisites, per https://docs.nginx.com/nginx/admin-guide/installing-nginx/installing-nginx-docker/#prerequisites
But I get it:
- We do need to update the command in step 5
- In such a long …

Include JWT license reference to installing-nginx-docker.md

---

content/nginx-one/agent/configure-instance-reporting/configuration-overview.md

Problem. From an internal user who tested the process. "I almost missed these configuration options"
Proposed solution: Expose table of NGINX Agent configuration options.
Location: https://docs.nginx.com/nginx-one/agent/configure-instance-reporting/configuration-overview/#configuration-via-environment-variables

fix: Expose Agent config options

---

.github/pull_request_template.md

Relative links seem broken in the template. Replacing with absolute links
[//]: # …

fix: replace rel links with abs links in template

---

content/nginxaas-azure/quickstart/security-controls/certificates.md

This note is no longer needed. From https://learn.microsoft.com/en-us/azure/private-link/network-security-perimeter-concepts:
> Network security perimeter is now generally available in all Azure public cloud regions.

fix: remove NSP warning

---

content/ngf/overview/product-telemetry.md

- Updates telemetry documentation to add information about Nginx One Console connection metric.

NGF: Update telemetry doc for nginx one console connection metric

---

content/nginx-one/_index.md

N1C front page. Glossary description not correct. (Accidental duplicate of changelog description)

fix: N1C update glossary description on front doc page

---

content/ngf/install/upgrade-version.md

The upgrade process for 2.1 isn't as straight forward as normal upgrades, due to the potential for downtime. The upgrade doc needs to be updated with this callout and the steps to take to avoid this scenario.
[//]: # "Include information on testing if relevant and …

NGF: Fix upgrade doc for 2.1 release

---

content/nic/configuration/policy-resource.md

- Adds website docs for new NIC cache policy
related NIC feature PR: https://github.com/nginx/kubernetes-ingress/pull/8005

add website docs for NIC cache policy

---

content/includes/nic/installation/create-custom-resources.md

This commit fixes a production URL link in NGINX Ingress Controller's instructions which should have been a Hugo reference shortcode.

feat: Fix erroneous upgrade link

---

content/nginx/_index.md

Remove card-layout from N+ landing page

---

content/nim/releases/known-issues.md

This PR cleans up the **Known Issues** for NGINX Instance Manager by removing entries that were incorrectly labeled as **“Won’t Fix.”**
- After auditing against Jira, we confirmed these items were either:
- **Fixed in later versions**, or
- **No longer reproducible**, and one did not warrant a release note.
- Their presence in the Known Issues doc as “Won’t Fix” was **incorrect** and created noise for readers.
- Removed all incorrectly labeled “Won’t Fix” entries from `nim/releases/known-issues.md`.
- Kept the page focused on **current, actionable issues** with valid workarounds or verified resolution info.
- 46022, 42133, 42119, 38782, 38596, 38488, 38041, 37498, 37437, 34185, 33307, 33160, 32718, 28758, 28683
- Improves accuracy and user trust by reflecting actual product status.
- …

docs(nim): remove closed "Won’t Fix" issues from Known Issues

---

content/nim/fundamentals/tech-specs.md
content/nim/system-configuration/configure-clickhouse.md

This PR:
- Adds a header for `trace_log` to the Config ClickHouse guide

Formatting edits to the Configure ClickHouse doc

---

content/nic/configuration/policy-resource.md

- Update `keyCache` doc in JWKS policy

update nic jwks keycache docs

---

content/nginx-one/agent/configure-instance-reporting/connect-using-squid.md

- Add example conf for domains
- Add full docker commmands
- Remove Macos from troubleshooting guide
[//]: # "For expediency, you can use screenshots to show small before and …

Remove instructions to setup squid with auth

---

content/nic/configuration/global-configuration/command-line-arguments.md
content/nic/configuration/proxy-buffers-configuration.md

- update NIC docs with correct cli arg

fix nic cli arg for autoadjust

---

content/nic/installation/installing-nic/installation-with-helm.md

Add spacing between CRD items to prevent mobile overflow.

fix: NIC Helm install: add spacing to prevent overflow

---

content/ngf/_index.md
content/nginxaas-azure/_index.md
content/nic/_index.md
content/nim/_index.md

This PR adds "F5" to the product names on the main landing pages for:
- F5 NGINX Instance Manager
- F5 NGINX Gateway Fabric
- F5 NGINX Ingress Controller
- F5 NGINX as a Service for Azure

Added F5 to product doc entry pages

---

static/nginxaas-azure/js/cost-calculator_v2.js

- Replaced broken `jQuery` usage with vanilla JS.
Before:
After:

Fixed N4A cost calculator

---

content/nap-waf/v5/admin-guide/policy-lifecycle-management.md

Added suggested offline solution for users who don’t want to download the security update pkgs from nginx repo.

Wafmc 13048 doc offline solution ap signatures

---

content/nic/configuration/policy-resource.md

fix ordering in NIC policy doc

---

content/nginx/admin-guide/basic-functionality/managing-configuration-files.md

A tiny fix/enhancement for https://docs.nginx.com/nginx/admin-guide/basic-functionality/managing-configuration-files/
- path for FreeBSD for NGINX Plus
- nginx -V and --config-path parameter that allows you to find out your config path
- Sentence-case titles, nbsp removal

fix: config path in managing-config-files

---

content/nginx/admin-guide/installing-nginx/installing-nginx-plus.md

A quick fix for Step 12 of https://docs.nginx.com/nginx/admin-guide/installing-nginx/installing-nginx-plus/#install_freebsd
Currently, the Linux path (/etc/nginx/nginx.conf) is used instead of FreeBSD (/usr/local/etc/nginx/nginx.conf).

fix: include for NGINX on FreeBSD

---

content/includes/nginxaas-azure/ssl-tls-prerequisites.md
content/nginxaas-azure/changelog.md
content/nginxaas-azure/getting-started/ssl-tls-certificates/overview.md
content/nginxaas-azure/known-issues.md
content/nginxaas-azure/quickstart/security-controls/certificates.md

This commit updates the NGINXaaS documentation to add instructions for fetching certificates via private endpoints.
[//]: # "For expediency, you can use screenshots to show …

feat: NGINXaaS - Certificate Fetch via Private Endpoint support

---

content/ngf/traffic-management/basic-routing.md

The [basic routing docs](https://docs.nginx.com/nginx-gateway-fabric/traffic-management/basic-routing/) for has multiple references to Gateway and HTTPRoute specs in the GatewayAPI docs.
These references currently don't take the user to the exact field that is references.
The goal of this change is to update those references
Closes https://github.com/nginx/nginx-gateway-fabric/issues/3975

Update references to Gateway API spec in NGF docs

---

_banners/waf-unification-notice.md
content/nic/configuration/global-configuration/command-line-arguments.md

Removed reference to old documentation as the old docs are not available any more

docs: Update WAF documentation banner content

---

content/nginx-one/nap-integration/overview.md

Based on latest WAF refactor, links from https://docs.nginx.com/nginx-one/nap-integration/overview no longer make sense

Update per WAF refactor

---

content/nginxaas-azure/app-protect/configure-waf.md
content/nginxaas-azure/changelog.md
content/nginxaas-azure/known-issues.md

- Removes restriction on the combination of both precompiled and custom policies in an NGINX config
[//]: # "For expediency, you can use screenshots to show small before and …

Remove restriction on combination of WAF policies

---

content/nic/configuration/policy-resource.md

Add missing `securityLogs` parameter to the NGINX Ingress Controller WAF policy configuration.

NIC: Add securityLogs table to WAF policy

---

content/nginx-one/agent/configure-instances/configure-agent-features.md

Removed 'connection' and 'agent-api' features from launch and environment variable examples. as these don't apply to v3
[//]: # "For expediency, you can use screenshots to …

docs: Update agent features configuration examples

---

.github/workflows/stale-branches.yml

Prunes all stale branches. All branches are considered stale after 90 days.

Add workflow to prune stale branches

---

content/nginx-one/agent/configure-instances/configure-agent-features.md

Update the Agent v3 features table with correct information.
[//]: # "If the …

Update agent v3 features table

---

content/waf/policies/configuration.md

Formatted the command for better readability.
[//]: # "If the changes were defined …

docs: Improve command formatting in configuration.md

---

content/waf/install/virtual-environment.md

Reorganize installation instructions for F5 WAF.
closes #1246 
[//]: # "If the …

Docs: WAF bare metal install OS order
